; Generated by Calypsi ISO C compiler for 65816

            .rtmodel version,"1"
            .rtmodel codeModel,"large"
            .rtmodel dataModel,"large"
            .rtmodel core,"65816"
            .rtmodel huge,"0"
            .rtmodel target,"snes"
            .rtmodel ppu,"1"
            .extern _Dp
            .extern _Vfp
;  /* ot6 C spike: smallest observable function. the trampoline stores the
;     result where the harness can assert it. */
;  unsigned char ot6_c_mix(unsigned char a, unsigned char b)
;  {
            .section farcode,text
            .public ot6_c_mix
ot6_c_mix:
;      return (unsigned char)(a * 2 + b + 1);
            asl     a
            clc
            adc     4,s
            inc     a
;  }
            rtl

