; Generated by Calypsi ISO C compiler for 65816

            .rtmodel version,"1"
            .rtmodel codeModel,"large"
            .rtmodel dataModel,"large"
            .rtmodel core,"65816"
            .rtmodel huge,"0"
            .rtmodel target,"snes"
            .rtmodel ppu,"1"
            .extern _Dp
            .extern _Vfp
;  /* ot6 C spike: smallest observable function. the trampoline
;     (Ot6CSpikeProbe, ff6/src/battle/ot6.asm) stores the result at the
;     witness word OT6_CWITNESS = $7e57ba, where battle_c.lua asserts it.
;     ($57ba sits in the write-watch-verified free strip next to
;     OT6_FONTDIRTY; the old home $57dc was inside vanilla's $57d5-$5854
;     battle name-scratch string.) */
;  unsigned char ot6_c_mix(unsigned char a, unsigned char b)
;  {
            .section farcode,text
            .public ot6_c_mix
ot6_c_mix:
;      return (unsigned char)(a * 2 + b + 1);
            asl     a
            clc
            adc     4,s
            inc     a
;  }
            rtl

