-- @suite savestate=zozo_clock_solved
-- field_healpolicy.lua -- H.fieldCare's healing policy: cast a cure spell
-- when somebody can, drink from the bag when nobody can.  Reads and pad
-- presses only (issue #75).
--
-- Owner, 2026-08-11: *"use tonics.  they're cheap, easy heals.  also early
-- game as we've modded it, healing with magic is pretty economical, given
-- the MP refresh on level up."*  OT6 restores HP and MP in full on level up
-- (ot6_progression.asm:3-6, called from battle_main.asm:16251), so MP spent
-- in a corridor comes back and a Tonic drunk in one does not.
--
-- The fixture is zozo_clock_solved: a caster who knows Cure and has MP to
-- spend, a bag of Tonics, and (as of the healthy-fixture campaign below) a
-- standing, undamaged party.  One starting state therefore drives the same
-- visit four ways, and the difference between the first two IS the
-- consumable saving.
--
-- NOTHING BELOW IS WRITTEN AS A LITERAL FROM THAT FIXTURE, and that is a
-- correction rather than a style preference.  This test used to be
-- zozo_arrival's, and it named LOCKE at 91 of 249, CELES at exactly 77 MP,
-- EDGAR at exactly 280, and exactly 6 Tonics.  On 2026-08-13 the route
-- started fighting and grinding its way to Zozo and healing between the
-- fights, so zozo_arrival began arriving with all four at full HP -- a
-- better fixture and a broken test, which failed on "LOCKE is the one who
-- needs it (314/314)".  The subject here is the RELATIONSHIP between the
-- branches (bag versus MP, and which of the two the policy reaches for),
-- never any particular number, so the roles are resolved from the fixture
-- at load: the patient is whoever is furthest below their maximum and knows
-- no cure, the healer is whoever knows Cure, and the refusal target is
-- whoever is already at full.
--
-- The one thing that used to be a fixture assumption -- that SOMEBODY is
-- meaningfully hurt -- stopped being one on 2026-08-18, when the
-- healthy-fixture repair campaign (fieldCare stops at damage sites;
-- tools/audit_party_hp.py) made every generated savestate ship standing and
-- undamaged, zozo_clock_solved included.  There is no fixture left upstream
-- that arrives hurt, by design, so this test now manufactures its own
-- patient: hurtPatient() below writes a reduced HP straight into one
-- Cure-less character's record after each reload.  That write is a
-- sanctioned focused-test expedient (tools/state_write_waivers.txt), not a
-- claim about play; the property under test -- the relationship between the
-- bag and cast branches -- is unchanged.
--
-- What this pins down:
--   1. M.calcMaxHpMp unpacks the boost code the way CalcMaxHPMP does.  A
--      table check against literal words rather than a fixture, because no
--      World of Balance roster has a boost bit set, so no route reaches the
--      arms that were wrong.
--   2. opts.magic=false: the patient is healed out of the bag.  Consumables
--      go down and nobody's MP moves.
--   3. The default policy: the patient is healed by the caster casting Cure.
--      Her MP goes down, the bag is untouched, and the patient ends at least
--      as healthy as the item run left him.
--   4. opts.mpFloor past her whole pool: she declines and the bag pays.
--      That is the branch a step takes when it wants its MP for the fight
--      it is walking toward.
--   5. A refusal driven by hand, to measure what the game leaves in zMosaic
--      afterwards.  The answer decides how any driver may test for a
--      refusal, and the test M.fieldCare used was wrong.
--   6. Case 3 also logs the whole visit's ZMENUSTATE trace, which is the check
--      research/field-care-menu.md section 9 asks for: every state number in
--      that document came from reading the assembly and none of it had been
--      observed running.
--
-- Not covered here, because no fixture generated by this chain has a party
-- where the only healer is also the only patient: a caster curing herself.
-- Measured instead in gen_ifrit_magicite's own log, where CELES's third
-- cast of the visit is on herself (221 -> 349).
--
-- Run it directly:
--   OT6_KEEP_RUNS=1 OT6_NO_PUBLISH=1 tools/tests/run.sh tools/tests/field_healpolicy.lua
local H = dofile("tools/tests/lib/ot6.lua")

local ZOZO = "build/states/zozo_clock_solved.mss.lua"
local CURE = 0x2D
local refuseState = nil       -- the menu state the case-5 refusal came from
local refuseTonics = nil      -- the bag's Tonic count before that refusal

-- The three roles, resolved from the booted fixture rather than named.
-- PATIENT is the member furthest below their own maximum who cannot cure
-- themselves, HEALER is a member who knows Cure, and FULL is somebody
-- already at their maximum, which case 5 needs so the game refuses a Tonic.
local PATIENT, HEALER, FULL = nil, nil, nil

-- The healthy-fixture campaign (fieldCare now stops at damage sites;
-- tools/audit_party_hp.py) means every generated savestate, zozo_clock_solved
-- included, ships its party standing and undamaged.  That is the fixture
-- getting better and this test's one remaining fixture assumption --
-- "somebody is meaningfully hurt" -- going false.  Rather than chase a
-- fixture upstream that still ships damage (none is left, by design), this
-- test manufactures its own patient: a direct write to one character's HP
-- word, the same $1600+37c record layout gen_*.lua and the battle tests
-- already poke.  Sanctioned as a focused-test expedient
-- (tools/state_write_waivers.txt); the property under test -- the
-- relationship between the bag and cast branches -- is unchanged, only the
-- fixture's "somebody hurt" precondition is now made true by hand instead
-- of assumed.  WOUNDED is resolved once (the first character who knows no
-- Cure) and rewritten after every reload of ZOZO, since the savestate
-- itself reverts to full health each time.
local WOUNDED = nil

local function hurtPatient()
  if not WOUNDED then
    for _, c in ipairs(H.partyMembers()) do
      if not H.knowsSpell(c, CURE) then WOUNDED = c; break end
    end
    H.assertEq(WOUNDED ~= nil, true,
      "the fixture has somebody who knows no Cure to cast as patient")
  end
  H.writeWord(0x1600 + 37 * WOUNDED + 9,
    math.floor(H.charMaxHp(WOUNDED) * 0.5))
end

local function resolveRoles()
  local worst = 1.0
  for _, c in ipairs(H.partyMembers()) do
    local frac = H.charHp(c) / H.charMaxHp(c)
    if H.knowsSpell(c, CURE) then
      HEALER = HEALER or c
    elseif frac < worst then
      worst, PATIENT = frac, c
    end
    if H.charHp(c) == H.charMaxHp(c) then FULL = FULL or c end
  end
  H.assertEq(PATIENT ~= nil, true,
    "the fixture has somebody hurt who knows no cure -- the case this " ..
    "whole test is about")
  H.assertEq(HEALER ~= nil, true, "the fixture has a caster who knows Cure")
  H.assertEq(FULL ~= nil, true,
    "the fixture has somebody at full HP for the refusal case")
  H.assertEq(H.charHp(PATIENT) < H.charMaxHp(PATIENT) * 0.95, true,
    string.format("the patient is below the threshold these cases heal to " ..
      "(char %d, %d/%d)", PATIENT, H.charHp(PATIENT), H.charMaxHp(PATIENT)))
  H.log(string.format("roles: patient=char %d (%d/%d hp), healer=char %d " ..
    "(%d/%d mp), full=char %d", PATIENT, H.charHp(PATIENT),
    H.charMaxHp(PATIENT), HEALER, H.charMp(HEALER), H.charMaxMp(HEALER),
    FULL))
end

-- ZMENUSTATE trace: one entry per distinct value, with a frame count, so a
-- 300-frame visit reads as a dozen lines instead of 300.
local trace, tracing = {}, false
emu.addEventCallback(function()
  if not tracing then return end
  local st = H.readByte(0x26)
  local last = trace[#trace]
  if last and last.st == st then last.n = last.n + 1
  else trace[#trace + 1] = { st = st, n = 1 } end
end, emu.eventType.startFrame)

local function traceText()
  local out = {}
  for _, e in ipairs(trace) do
    out[#out + 1] = string.format("$%02X x%d", e.st, e.n)
  end
  return table.concat(out, " -> ")
end

local function bag() return H.invCountOf(0xE8) + H.invCountOf(0xE9) end

local itemRun, magicRun = {}, {}

H.run({ maxFrames = 200000 }, {
  H.waitFrames(20),

  -- 1. the boost unpack, checked against the source's own fall-through
  -- chain (menu_common.asm:2398-2412): code 0 = base, 1 = +25%, 2 = +50%,
  -- 3 = +12.5%.  Codes 2 and 3 were swapped here, so 2 and 3 below are the
  -- clauses that fail on the old unpack.
  H.call(function()
    H.assertEq(H.calcMaxHpMp(0x0000 | 200, 9999), 200, "boost code 0 is base")
    H.assertEq(H.calcMaxHpMp(0x4000 | 200, 9999), 250, "boost code 1 is +25%")
    H.assertEq(H.calcMaxHpMp(0x8000 | 200, 9999), 300, "boost code 2 is +50%")
    H.assertEq(H.calcMaxHpMp(0xC000 | 200, 9999), 225, "boost code 3 is +12.5%")
    H.assertEq(H.calcMaxHpMp(0x3FFF, 9999), 9999, "max HP clamps at 9999")
    H.assertEq(H.calcMaxHpMp(0x8000 | 900, 999), 999, "max MP clamps at 999")
    -- Cure's price is read from the ROM table the field menu itself prices
    -- from (skills.asm:1056-1060), so this is the number the policy budgets
    -- against rather than a copy of mp-economy.md.
    H.log(string.format("MP costs: Cure=%d Cure2=%d Cure3=%d",
      H.spellMpCost(0x2D), H.spellMpCost(0x2E), H.spellMpCost(0x2F)))
    H.assertEq(H.spellMpCost(0x2D) > 0, true, "Cure has a price in MagicProp")
  end),

  -- 2. the bag branch: same fixture, magic switched off
  H.loadState(ZOZO),
  H.waitFrames(30),
  H.waitUntil(function() return H.hasControl() end, 600, "field control", 5),
  H.call(function()
    hurtPatient()
    resolveRoles()
    H.assertEq(H.knowsSpell(HEALER, CURE), true, "the healer knows Cure here")
    H.assertEq(H.knowsSpell(PATIENT, CURE), false, "the patient does not")
    itemRun.bag, itemRun.mp = bag(), H.charMp(HEALER)
  end),
  H.fieldCare({ tag = "zozo bag", threshold = 0.95, magic = false }),
  H.call(function()
    itemRun.spent = itemRun.bag - bag()
    itemRun.hp = H.charHp(PATIENT)
    H.log(string.format("bag branch: %d consumables spent, healer mp %d -> " ..
      "%d, patient %d/%d", itemRun.spent, itemRun.mp, H.charMp(HEALER),
      itemRun.hp, H.charMaxHp(PATIENT)))
    H.assertEq(itemRun.spent > 0, true,
      "with magic off the bag is what pays")
    H.assertEq(H.charMp(HEALER), itemRun.mp,
      "and no MP is spent doing it")
    H.assertEq(H.hasControl() and H.tileAligned(), true,
      "the menu is closed and the party has control back")
  end),

  -- 3. the cast branch: same fixture, default policy
  H.loadState(ZOZO),
  H.waitFrames(30),
  H.waitUntil(function() return H.hasControl() end, 600, "field control", 5),
  H.call(function()
    hurtPatient()
    magicRun.bag, magicRun.mp = bag(), H.charMp(HEALER)
    trace, tracing = {}, true
  end),
  H.fieldCare({ tag = "zozo cast", threshold = 0.95 }),
  H.call(function()
    tracing = false
    magicRun.spent = magicRun.bag - bag()
    magicRun.hp = H.charHp(PATIENT)
    H.log("ZMENUSTATE trace: " .. traceText())
    H.log(string.format("cast branch: %d consumables spent, healer mp %d -> " ..
      "%d, patient %d/%d", magicRun.spent, magicRun.mp, H.charMp(HEALER),
      magicRun.hp, H.charMaxHp(PATIENT)))
    H.assertEq(H.charMp(HEALER) < magicRun.mp, true,
      "the healer paid for the heal out of her own MP")
    H.assertEq(magicRun.spent, 0,
      "and the bag was not opened at all")
    H.assertEq(magicRun.hp >= itemRun.hp, true, string.format(
      "casting left the patient at least as healthy as drinking did " ..
      "(%d vs %d)", magicRun.hp, itemRun.hp))
    H.assertEq(magicRun.hp >= H.charMaxHp(PATIENT) * 0.95, true,
      string.format("the patient is back above the threshold (%d/%d)",
        magicRun.hp, H.charMaxHp(PATIENT)))
    H.assertEq(H.hasControl() and H.tileAligned(), true,
      "the menu is closed and the party has control back")
    H.log(string.format(
      "SAVING at this stop: %d consumables, paid for with %d MP",
      itemRun.spent - magicRun.spent, magicRun.mp - H.charMp(HEALER)))
  end),

  -- 4. the MP floor.  Same fixture and the same caster as case 3, with the
  -- floor raised past her whole pool: she can still cast as far as the game
  -- is concerned, and the policy declines and opens the bag instead.  This
  -- is the branch a step takes when it wants its MP kept for the fight it
  -- is walking toward.
  H.loadState(ZOZO),
  H.waitFrames(30),
  H.waitUntil(function() return H.hasControl() end, 600, "field control", 5),
  H.call(function()
    hurtPatient()
    magicRun.floorBag, magicRun.floorMp = bag(), H.charMp(HEALER)
  end),
  H.fieldCare({ tag = "zozo mp floor", threshold = 0.95, mpFloor = 999 }),
  H.call(function()
    H.assertEq(H.charMp(HEALER), magicRun.floorMp,
      "the floor kept every point of the healer's MP")
    H.assertEq(magicRun.floorBag - bag() > 0, true,
      "so the bag paid instead")
    H.assertEq(H.charHp(PATIENT) >= H.charMaxHp(PATIENT) * 0.95, true,
      "and the patient is topped up either way")
  end),

  -- 5. the refusal cell, measured rather than assumed.
  --
  -- CheckCanUseItem refuses a Tonic on a character already at full HP
  -- (item.asm:2249-2258), and the refusal is reported by starting the
  -- mosaic task.  What that task leaves behind decides how a driver may
  -- test for a refusal: it writes the eight bytes $17 $27 $37 $47 $37 $27
  -- $17 $07 and terminates without zeroing the cell
  -- (field_menu.asm:3820-3844), and nothing re-zeroes it after menu init
  -- (menu_init_2.asm:506).
  --
  -- So the counter-example below is the whole point: forty frames after one
  -- refusal, $B5 is still nonzero while its high nibble has gone back to
  -- zero.  A driver testing `$B5 ~= 0` reads every later plan in the same
  -- menu visit as refused without pressing anything; the high nibble is the
  -- edge.  M.fieldCare tested the whole byte until this measurement.
  H.loadState(ZOZO),
  H.waitFrames(30),
  H.waitUntil(function() return H.hasControl() end, 600, "field control", 5),
  H.call(function() refuseTonics = H.invCountOf(0xE8) end),
  (function()
    -- A refusal driven by hand, because no fixture on the route produces
    -- one: M.fieldCare's own planner never proposes a pair the game will
    -- turn down.  A Tonic ($E8) on whoever the fixture ships at full HP.
    local TONIC = 0xE8
    local phase, done = 0, false
    local function steer(cur, row)
      if cur == row then return { "a" } end
      return { [cur < row and "down" or "up"] = true }
    end
    return H.driveUntil(function() return done end, 4000, {
      H.call(function()
        phase = (phase + 1) % 12
        local st, held = H.readByte(0x26), nil
        -- Record WHERE the mosaic started.  Twenty-one places in src/menu
        -- create that task (section 3 of the research note), so "the cell
        -- went nonzero" on its own would not prove this drive produced the
        -- refusal it meant to; refuseState is asserted below.
        if (H.readByte(0xB5) & 0xF0) ~= 0 then
          refuseState = st; done = true; H.setPad({}); return
        end
        if st == 0x05 then held = steer(H.readByte(0x4B), 0)
        elseif st == 0x08 then held = steer(H.readByte(0x4B), H.invSlotOf(TONIC))
        elseif st == 0x19 then
          held = (H.readByte(0x4B) == H.invSlotOf(TONIC)) and { "a" } or { "b" }
        elseif st == 0x70 then
          local slot
          for s = 0, 3 do if H.readByte(0x69 + s) == FULL then slot = s end end
          held = steer(H.readByte(0x4B), slot)
        elseif st == 0x17 or st == 0x77 then held = { "b" }
        elseif st ~= 0x00 and st ~= 0x01 and st ~= 0x02 and st ~= 0x07
           and st ~= 0x04 and st ~= 0x03 and st ~= 0x6F then
          held = { "x" }                        -- still on the map: open it
        else H.setPad({}); return end
        H.setPad(phase < 4 and held or {})
      end),
    }, "drive a Tonic onto the full-HP member")
  end)(),
  H.release(),
  H.call(function()
    H.assertEq(refuseState, 0x70,
      "the refusal came from the item target window, not somewhere else")
    H.assertEq((H.readByte(0xB5) & 0xF0) ~= 0, true,
      "and it is announced in zMosaic's high nibble")
    H.assertEq(H.invCountOf(0xE8), refuseTonics, "the Tonic was not spent")
    H.assertEq(H.charHp(FULL), H.charMaxHp(FULL),
      "the refusal target is untouched, still at full HP")
  end),
  H.waitFrames(40),
  H.call(function()
    local b5 = H.readByte(0xB5)
    H.log(string.format("zMosaic 40 frames after the refusal: $%02X", b5))
    H.assertEq(b5 ~= 0, true,
      "zMosaic is still set long after the animation ended -- it is never "
      .. "cleared, so `$B5 ~= 0` cannot mean 'this plan was refused'")
    H.assertEq(b5 & 0xF0, 0,
      "...while the high nibble has gone back to zero, which is the edge "
      .. "a driver can test")
  end),
})
