#!/usr/bin/env python3
"""fightswingslab.py -- what the driver's Fight model costs at the controls (#235).

    python3 tools/tests/fightswingslab.py model
    python3 tools/tests/fightswingslab.py write
    python3 tools/tests/fightswingslab.py run [--seeds 0,7,13,...] [--jobs N] arm
    python3 tools/tests/fightswingslab.py aggregate [arm ...]

`M.fightSwings` returned the SWING count (`1 + 2*boost` for one weapon)
where both its callers wanted the LANDED-HIT count (`1 + boost`; the
whiffing half is the empty hand -- ot6_boost.asm's own header, and the
#219 lab's histogram, `build/attempts/fight-vs-ability/lab/fight-vs-
ability/mechanic.txt`).  `fightChips` counts one chip per landed hit and
`keyBoost` picks a boost depth off `fightChips`, so the model's error is
a strategy error.  This lab asks how big a one, twice:

----------------------------------------------------------------------
`model` -- the decision table, no emulator
----------------------------------------------------------------------
Runs BOTH models through the shipped `M.keyBoost` for every (shields
standing, bank, hands) a World-of-Balance gauge can present, and prints
the cells where the chosen boost moves and the cells where the driver
claimed a break it could not land.  Plain arithmetic, so the consequence
is bounded before a single frame is emulated -- and so a claim about
"5- and 6-shield gauges" is checked rather than inherited.

----------------------------------------------------------------------
`write` / `run` / `aggregate` -- the in-play arm
----------------------------------------------------------------------
One fight: **battle 70, IFRIT and SHIVA**, both authored 6 shields
(`ot6_hud.asm`: $0109 6 OT6_PIERCE, $0108 6 OT6_SLASH) -- two of the four
bodies #235 names.  The fixture is the tracked `ifrit_entry` savestate,
"map 264 (3,7) facing IFRIT, one A-press from battle 70", and the party
it carries is four ONE-WEAPON characters (LOCKE $02 Guardian pierce,
EDGAR $0A MithrilBlade slash, SABIN $53 MetalKnuckle slash, CELES $0A
slash), which is exactly the shape the model got wrong.

The fight is played by the shipped library fighter under
`gen_ifrit_magicite.lua`'s own options, verbatim -- `tactical = false`,
`boost`, `bank = 3`, real items, `healPercent = 80`, CELES on Ice -- so
this measures the driver the route actually runs, not a lab-only policy.
`OT6_SEED_SHIFT` idles the boot point by N game-clock ticks, which is the
spread narshedescentlab.py uses; the seed each battle actually drew is
read off InitBattle's own store and printed, so seed collisions are
visible rather than assumed.

The measurement is read-only.  Four CPU exec observers, all borrowed from
the #219 lab so the two cannot count differently:

    ExecCmd@battle_code   park the acting character, its command, banked
                          and revealed BP, both hands' item ids, and the
                          target gauge
    Ot6WeaponClass        one exec per hand per swing: SWINGS ATTEMPTED
    Ot6HitJoin            one exec per landed hit per target: LANDED HITS
    SaveForMimic          the action resolved -- emit the row, with the
                          target's shields before and after

Plus a shield watch on both bodies, so "the break landed" is a gauge
reaching zero, not an inference.

An arm is just a directory name: the model under test is whatever the
working tree's `lib/ot6.lua` says.  Run `before`, apply the fix, run
`after`.  Every attempt is kept, wipes and frame-cap runs included;
nothing selects a run.
"""
import argparse
import concurrent.futures
import os
import re
import subprocess
import sys
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "build", "lab", "fight-swings")
LAB = os.path.join(OUT, "lab.lua")

LAB_LUA = r'''-- AUTOGENERATED by tools/tests/fightswingslab.py -- do not edit.
-- The fight-swings lab (#235): battle 70 (IFRIT $0109 / SHIVA $0108, six
-- authored shields each) from the tracked ifrit_entry fixture, played by
-- the shipped library fighter under gen_ifrit_magicite.lua's own options.
-- Read-only measurement: nothing below presses a button except through
-- the fighter, and nothing writes a byte.
local H = dofile("tools/tests/lib/ot6.lua")

local STATE = "build/states/ifrit_entry.mss.lua"
local IFRIT, SHIVA = 0x0109, 0x0108
local SH_CUR, BRK_TICKS = 0x3E40, 0x3E90
local MON_HP, MON_PRESENT = 0x3BFC, 0x3AA8
local PHP = 0x3BF4
local BP, PEND, CHARIX = 0x3E9C, 0x3E9D, 0x3ED9
local CMDNAME = {
  [0x00] = "Fight", [0x01] = "Item", [0x02] = "Magic", [0x05] = "Steal",
  [0x07] = "SwdTech", [0x09] = "Tools", [0x0A] = "Blitz", [0x0B] = "Runic",
  [0x0F] = "Slot", [0x12] = "Mimic", [0x15] = "Def", [0x19] = "Summon",
}

local function map() return H.mapId() & 0x1ff end
local function sw(id) return (H.readByte(0x1E80 + (id >> 3)) >> (id & 7)) & 1 end
local function seq(steps) return H.cond(function() return true end, steps) end
local function mshields(m) return H.readByte(SH_CUR + m * 2) end
local function mticks(m)   return H.readByte(BRK_TICKS + m * 2) end
local function mhp(m)      return H.readWord(MON_HP + m * 2) end
local function onfield(m)  return H.readByte(MON_PRESENT + m * 2) & 1 end
local function mspecies(m) return H.readWord(0x57C0 + m * 2) end

local ISLOT, SSLOT
local turns = 0                      -- party actions resolved this battle
local battleF0 = nil
local brokeAt = {}                   -- slot -> { turn, frame } of the first break
local acts = {}                      -- buffered [fs-act] lines
local seedDrawn = nil

-- ------------------------------------------- the driver's own claim ----
-- The keyed rule (#174) announces, in the driver's own log line, the boost
-- it picked and the chips it believes that lands on the gauge standing now.
-- That claim is the thing #235 is about, so it is caught at the moment it
-- is made and carried onto the action it was made for, rather than
-- correlated afterwards by guesswork.  Reading the driver's log is
-- observation: H.log is wrapped, every message is passed straight through,
-- and nothing here changes a decision.
local claim = {}                     -- actor slot -> the claim it planned on
local baseLog = H.log
H.log = function(msg)
  if type(msg) == "string" then
    local a, what, chips, slot, need =
      msg:match("actor=(%d+) KEYED: (.-) lands (%d+) chip%(s%) on slot (%d+)'s (%d+) shield")
    if a then
      claim[tonumber(a)] = {
        what = what, chips = tonumber(chips), slot = tonumber(slot),
        need = tonumber(need),
        breaks = msg:find("the smallest boost that breaks this turn") ~= nil,
      }
    end
  end
  return baseLog(msg)
end

-- ------------------------------------------------------- the observers --
-- Lifted from tools/tests/fightvsabilitylab.py's block so the two arms of
-- the #219/#235 pair cannot count a swing or a hit differently.
local CUR = nil
local function hands(slot)
  local c = H.readByte(CHARIX + slot * 2)
  local r = H.readByte(0x1600 + 37 * c + 0x1F)
  local l = H.readByte(0x1600 + 37 * c + 0x20)
  local n = 0
  if H.isWeapon(r) then n = n + 1 end
  if H.isWeapon(l) then n = n + 1 end
  return n, r, l
end
local function stageSlot()
  -- the body an untargeted swing meets: the on-field monster with HP
  for m = 0, 5 do
    if onfield(m) == 1 and mhp(m) > 0 then return m end
  end
  return nil
end

local function armObservers()
  local a = {}
  a.cmd = H.sym("ExecCmd@battle_code")
  a.wc  = H.sym("Ot6WeaponClass")
  a.hj  = H.sym("Ot6HitJoin")
  a.sf  = H.sym("SaveForMimic")
  emu.addMemoryCallback(function()
    local x = emu.getState()["cpu.x"] & 0xFFFF
    if x >= 8 or x % 2 ~= 0 then CUR = nil return end
    local cmd = H.readByte(0xB5)
    if cmd >= 0x1E then CUR = nil return end
    local slot = x // 2
    local nh, rh, lh = hands(slot)
    local tgt = stageSlot()
    CUR = {
      x = x, slot = slot, cix = H.readByte(CHARIX + x), cmd = cmd,
      atk = H.readByte(0xB6), bp = H.readByte(BP + x),
      rev = H.readByte(PEND + x), hands = nh, rh = rh, lh = lh,
      tgt = tgt, sh0 = tgt and mshields(tgt) or -1,
      hp0 = tgt and mhp(tgt) or 0, swings = 0, hits = 0,
    }
  end, emu.callbackType.exec, a.cmd, a.cmd)
  emu.addMemoryCallback(function()
    if not CUR then return end
    local x = emu.getState()["cpu.x"] & 0xFFFF
    if (x & 0xFFFE) ~= CUR.x then return end
    CUR.swings = CUR.swings + 1
  end, emu.callbackType.exec, a.wc, a.wc)
  emu.addMemoryCallback(function()
    if not CUR then return end
    if (emu.getState()["cpu.y"] & 0xFFFF) < 8 then return end
    CUR.hits = CUR.hits + 1
  end, emu.callbackType.exec, a.hj, a.hj)
  emu.addMemoryCallback(function()
    local c = CUR
    if not c then return end
    CUR = nil
    turns = turns + 1
    local sh1 = c.tgt and mshields(c.tgt) or -1
    local hp1 = c.tgt and mhp(c.tgt) or 0
    local k = claim[c.slot]
    claim[c.slot] = nil
    acts[#acts + 1] = string.format(
      "[fs-act] turn=%d f%d slot=%d char=%02X %s($%02X) bp=%d rev=%d "
      .. "hands=%d rh=$%02X lh=$%02X tgt=%s sh=%d->%d chips=%d "
      .. "swings=%d hits=%d dmg=%d claim=%s",
      turns, H.frame, c.slot, c.cix, CMDNAME[c.cmd] or "?", c.cmd,
      c.bp, c.rev, c.hands, c.rh, c.lh, tostring(c.tgt), c.sh0, sh1,
      (c.sh0 >= 0 and sh1 >= 0) and (c.sh0 - sh1) or 0,
      c.swings, c.hits, c.hp0 - hp1,
      k and string.format("%s/%dchips/%dsh/%s", (k.what:gsub("%s+", "_")),
                          k.chips, k.need, k.breaks and "breaks" or "best")
        or "-")
  end, emu.callbackType.exec, a.sf, a.sf)
  -- the battle seed InitBattle actually drew, for collision detection
  local ok, sa = pcall(function() return H.seedStoreAddr() end)
  if ok then
    emu.addMemoryCallback(function()
      if seedDrawn == nil then
        seedDrawn = emu.getState()["cpu.a"] & 0xFF
      end
    end, emu.callbackType.exec, sa, sa)
  end
end

local function flush()
  for _, l in ipairs(acts) do H.log(l) end
  acts = {}
end

-- --------------------------------------------------------- the fighter --
-- gen_ifrit_magicite.lua's own options, verbatim.
local F = H.newFightDriver("fslab", { tactical = false, boost = true, bank = 3,
  items = true, healPercent = 80, cadence = 12,
  magic = { [6] = { spell = 0x01, boost = false } } })

local wiped, hb, ph, giveUp = 0, 0, 0, 0
local outcome, tEnd = "none", nil

H.run({ maxFrames = 200000, allowGameOver = true }, {
  H.waitFrames(20),
  H.loadState(STATE),
  H.waitFrames(10),
  H.waitUntil(function()
    return H.hasControl() and H.tileAligned() and not H.dialogWaiting()
       and (emu.getState()["ppu.screenBrightness"] or 0) >= 15
  end, 3000, "control on map 264", 10),
  H.call(function()
    H.assertEq(map(), 264, "booted onto map 264, the Ifrit/Shiva alcove")
    H.assertEq(H.fieldX() == 3 and H.fieldY() == 7, true,
      "standing at (3,7), one A-press from battle 70")
    armObservers()
    for _, m in ipairs(H.partyWeapons()) do
      H.log(string.format("[fs-gear] char=%02X %s hand item=$%02X class=$%02X",
        m.char, m.hand, m.item, H.weaponClass(m.item)))
    end
  end),
  -- A into IFRIT -> _cc7937 -> battle 70
  H.driveUntil(function() return H.battleLoadStarted() end, 6000, {
    H.hold({ "a", "down" }), H.waitFrames(4), H.hold({ "down" }), H.waitFrames(4),
  }, "A into IFRIT -> battle 70"),
  H.release(),
  H.waitUntil(function() return H.battleActive() end, 900, "battle 70 active", 30),
  H.waitFrames(90),
  H.call(function()
    H.assertEq(H.formationHas({ [IFRIT] = true }), true, "battle 70 has IFRIT")
    H.assertEq(H.formationHas({ [SHIVA] = true }), true, "battle 70 has SHIVA")
    for m = 5, 0, -1 do
      if mspecies(m) == IFRIT then ISLOT = m end
      if mspecies(m) == SHIVA then SSLOT = m end
    end
    H.assertEq(mshields(ISLOT), 6, "ifrit opens with his authored 6 shields")
    H.assertEq(mshields(SSLOT), 6, "shiva opens with her authored 6 shields")
    battleF0 = H.frame
    H.log(string.format("[fs-open] f%d seed=%s ifr slot=%d hp=%d sh=%d | "
      .. "shv slot=%d hp=%d sh=%d", H.frame,
      seedDrawn and string.format("$%02X", seedDrawn) or "?",
      ISLOT, mhp(ISLOT), mshields(ISLOT), SSLOT, mhp(SSLOT), mshields(SSLOT)))
  end),
  H.waitUntil(function() return onfield(ISLOT) == 1 end, 3600,
    "ifrit takes the stage", 10),
  H.waitFrames(90),
  H.driveUntil(function()
    if (H.gameOverFired or 0) > 0 then return true end
    if wiped >= 120 then return true end
    return not H.battleLoadStarted() and not H.partyWipedInBattle()
  end, 120000, {
    H.call(function()
      hb = hb + 1
      wiped = H.partyWipedInBattle() and wiped + 1 or 0
      for _, m in ipairs({ ISLOT, SSLOT }) do
        if not brokeAt[m] and mshields(m) == 0 and mticks(m) ~= 0 then
          brokeAt[m] = { turn = turns, frame = H.frame }
          H.log(string.format("[fs-break] slot=%d turn=%d f%d (+%d)", m,
            turns, H.frame, H.frame - (battleF0 or H.frame)))
        end
      end
      if hb % 600 == 0 then
        flush()
        H.log(string.format("[fs-watch] f%d ifr hp=%d sh=%d tk=%d fld=%d | "
          .. "shv hp=%d sh=%d tk=%d | party %d/%d/%d/%d | turns=%d",
          H.frame, mhp(ISLOT), mshields(ISLOT), mticks(ISLOT), onfield(ISLOT),
          mhp(SSLOT), mshields(SSLOT), mticks(SSLOT),
          H.readWord(PHP), H.readWord(PHP + 2), H.readWord(PHP + 4),
          H.readWord(PHP + 6), turns))
      end
      F.frame()
    end),
  }, "battle 70, played by the shipped fighter"),
  H.call(function() F.idle(); H.setPad({}); tEnd = H.frame; flush() end),
  H.driveUntil(function()
    giveUp = giveUp + 1
    return sw(0x0060) == 1 or giveUp >= 3000
  end, 3200, {
    H.call(function()
      ph = (ph + 1) % 8
      if not H.hasControl() then H.setPad(ph < 4 and { "a" } or {})
      else H.setPad({}) end
    end),
  }, "the _cc7937 tail flips $0060 (or the loss shows itself)"),
  H.call(function()
    H.setPad({})
    flush()
    if sw(0x0060) == 1 then outcome = "won"
    elseif wiped >= 120 or (H.gameOverFired or 0) > 0 then outcome = "wiped"
    else outcome = "none" end
    local function brk(m)
      local b = brokeAt[m]
      return b and string.format("%d", b.turn) or "-"
    end
    local function brkf(m)
      local b = brokeAt[m]
      return b and string.format("%d", b.frame - (battleF0 or 0)) or "-"
    end
    H.log(string.format(
      "[result] arm=@ARM@ shift=@SHIFT@ seed=%s outcome=%s t=%d turns=%d "
      .. "ifr_break_turn=%s ifr_break_t=%s shv_break_turn=%s shv_break_t=%s "
      .. "ifr_hp=%d shv_hp=%d",
      seedDrawn and string.format("%02X", seedDrawn) or "??", outcome,
      (tEnd or H.frame) - (battleF0 or 0), turns,
      brk(ISLOT), brkf(ISLOT), brk(SSLOT), brkf(SSLOT),
      mhp(ISLOT), mhp(SSLOT)))
    H.screenshot("fslab_end")
  end),
})
'''


# ------------------------------------------------------------ model ------
def model_table():
    """Both models through keyBoost, for every gauge the WoB presents.

    The two models are the arithmetic, transcribed from the two versions of
    the library function; keyBoost's own rule is re-implemented here in the
    two lines it is, so the table is derivable by hand from this file.
    """
    def old(hands, b):
        return (2 + 2 * b) if hands == 2 else (1 + 2 * b)

    def new(hands, b):
        return (2 + 2 * b) if hands == 2 else (1 + b)

    def key_boost(chips_at, need, bank):
        if need <= 0 or chips_at(0) <= 0:
            return None
        for b in range(bank + 1):
            if chips_at(b) >= need:
                return b, True          # claims the break this turn
        return bank, False

    print("keyBoost's chosen depth, every (shields standing, bank, hands).")
    print("`claim` is whether the driver believed the break lands THIS turn.")
    print()
    hdr = "%-6s %-5s %-5s | %-5s %-5s | %-5s %-5s | %s" % (
        "hands", "need", "bank", "old", "claim", "new", "claim", "verdict")
    print(hdr)
    print("-" * len(hdr))
    moved = falseclaim = 0
    for hands in (1, 2):
        for need in range(1, 9):
            for bank in range(0, 4):
                o = key_boost(lambda b: old(hands, b), need, bank)
                n = key_boost(lambda b: new(hands, b), need, bank)
                if o is None and n is None:
                    continue
                ob, oc = o
                nb, nc = n
                # the ROM's own ceiling, which is what `new` models
                reachable = new(hands, bank) >= need
                notes = []
                if ob != nb:
                    notes.append("DEPTH %d->%d" % (ob, nb))
                    moved += 1
                if oc and not reachable:
                    notes.append("FALSE CLAIM (ceiling %d < %d)"
                                 % (new(hands, bank), need))
                    falseclaim += 1
                if not notes:
                    continue
                print("%-6d %-5d %-5d | %-5d %-5s | %-5d %-5s | %s" % (
                    hands, need, bank, ob, oc, nb, nc, "; ".join(notes)))
    print()
    print("cells where the chosen depth moves: %d" % moved)
    print("cells where the old model claimed a break the ROM cannot land: %d"
          % falseclaim)
    print()
    print("(two-weapon rows never appear: the pair branch was already right.)")


# ------------------------------------------------------------ write ------
def write(arm, shift, path=None):
    src = LAB_LUA.replace("@ARM@", arm).replace("@SHIFT@", str(shift))
    path = path or os.path.join(OUT, "lab-%s.lua" % arm)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(src)
    return path


# -------------------------------------------------------------- run ------
def run_one(arm, seed):
    d = os.path.join(OUT, arm)
    os.makedirs(d, exist_ok=True)
    # one lab file per seed: the arm and the shift are stamped into its own
    # [result] line, and two seeds running at once never share a path
    per = os.path.join(d, "lab-seed%02d.lua" % seed)
    write(arm, seed, per)
    log = os.path.join(d, "seed%02d.log" % seed)
    env = dict(os.environ)
    env.update({
        "OT6_RETRIES": "1", "OT6_SEED_SHIFT": str(seed),
        "OT6_NO_PUBLISH": "1",
        "OT6_TIMEOUT": env.get("OT6_TIMEOUT", "2400"),
        "OT6_ARTIFACT_DIR": os.path.join(d, "seed%02d" % seed),
        "OT6_WORKER": "fswings-%s-%02d" % (arm, seed),
    })
    os.makedirs(env["OT6_ARTIFACT_DIR"], exist_ok=True)
    with open(os.path.join(d, "seed%02d.out" % seed), "w") as out:
        rc = subprocess.run(["sh", os.path.join(ROOT, "tools/tests/run.sh"),
                             per, log],
                            cwd=ROOT, env=env, stdout=out,
                            stderr=subprocess.STDOUT).returncode
    return arm, seed, rc, summarize(log)


# -------------------------------------------------------- reading a log --
PASS = re.compile(r"^\[ot6\] PASS \(frame (\d+)\)")
FAILV = re.compile(r"^\[ot6\] FAIL: (.*)")
RESULT = re.compile(r"^\[ot6\] \[result\] (.*)")
ACT = re.compile(r"^\[ot6\] \[fs-act\] turn=(\d+) f(\d+) slot=(\d+) "
                 r"char=([0-9A-F]{2}) (\S+)\(\$[0-9A-F]{2}\) bp=(\d+) "
                 r"rev=(\d+) hands=(\d+) rh=\$([0-9A-F]{2}) lh=\$([0-9A-F]{2}) "
                 r"tgt=(\S+) sh=(-?\d+)->(-?\d+) chips=(-?\d+) "
                 r"swings=(\d+) hits=(\d+) dmg=(-?\d+) claim=(\S+)")
KEYED = re.compile(r"^\[ot6\] \[fslab\] actor=(\d+) KEYED: (.*?) lands (\d+) "
                   r"chip\(s\) on slot (\d+)'s (\d+) shield\(s\) -- (.*)")
BREAK = re.compile(r"^\[ot6\] \[fs-break\] slot=(\d+) turn=(\d+) f(\d+)")
GEAR = re.compile(r"^\[ot6\] \[fs-gear\] (.*)")


def kv(s):
    out = {}
    for p in s.split():
        if "=" in p:
            k, v = p.split("=", 1)
            out[k] = v
    return out


def summarize(log):
    r = dict(verdict="NONE", frame=None, fail="", result=None, acts=[],
             keyed=[], breaks=[], gear=[])
    if not os.path.exists(log):
        r["fail"] = "no log"
        return r
    for line in open(log, errors="replace"):
        line = line.rstrip("\n")
        m = PASS.match(line)
        if m:
            r["verdict"], r["frame"] = "PASS", int(m.group(1))
            continue
        m = FAILV.match(line)
        if m:
            r["verdict"], r["fail"] = "FAIL", m.group(1)[:200]
            continue
        m = RESULT.match(line)
        if m:
            r["result"] = kv(m.group(1))
            continue
        m = ACT.match(line)
        if m:
            g = m.groups()
            r["acts"].append(dict(
                turn=int(g[0]), f=int(g[1]), slot=int(g[2]), char=g[3],
                cmd=g[4], bp=int(g[5]), rev=int(g[6]), hands=int(g[7]),
                rh=g[8], lh=g[9], tgt=g[10], sh0=int(g[11]), sh1=int(g[12]),
                chips=int(g[13]), swings=int(g[14]), hits=int(g[15]),
                dmg=int(g[16]), claim=g[17]))
            continue
        m = KEYED.match(line)
        if m:
            r["keyed"].append(dict(actor=int(m.group(1)), what=m.group(2),
                                   chips=int(m.group(3)), slot=int(m.group(4)),
                                   need=int(m.group(5)), why=m.group(6)))
            continue
        m = BREAK.match(line)
        if m:
            r["breaks"].append((int(m.group(1)), int(m.group(2))))
            continue
        m = GEAR.match(line)
        if m:
            r["gear"].append(m.group(1))
    return r


def aggregate(arms):
    """Per arm: the per-seed result table, the Fight swing/hit ladder as this
    ROM played it, and every keyed claim with whether it came true."""
    for arm in arms:
        d = os.path.join(OUT, arm)
        logs = sorted(f for f in os.listdir(d) if f.endswith(".log")) \
            if os.path.isdir(d) else []
        print("== %s (%d log%s) ==" % (arm, len(logs),
                                       "" if len(logs) == 1 else "s"))
        if not logs:
            print("  (nothing run)\n")
            continue
        print("%-6s %-5s %-7s %8s %6s %10s %10s %s" % (
            "shift", "seed", "outcome", "frames", "turns", "ifr_break",
            "shv_break", "verdict"))
        seen = defaultdict(list)
        ladder = defaultdict(lambda: defaultdict(int))
        claims = []
        for name in logs:
            s = summarize(os.path.join(d, name))
            res = s["result"] or {}
            print("%-6s %-5s %-7s %8s %6s %10s %10s %s" % (
                res.get("shift", "?"), "$" + res.get("seed", "??"),
                res.get("outcome", "-"), res.get("t", "-"),
                res.get("turns", "-"),
                "t%s/f%s" % (res.get("ifr_break_turn", "-"),
                             res.get("ifr_break_t", "-")),
                "t%s/f%s" % (res.get("shv_break_turn", "-"),
                             res.get("shv_break_t", "-")),
                s["verdict"] + ((" " + s["fail"][:40]) if s["fail"] else "")))
            if res.get("seed"):
                seen[res["seed"]].append(res.get("shift"))
            for a in s["acts"]:
                if a["cmd"] == "Fight":
                    ladder[(a["hands"], a["rev"])][a["hits"]] += 1
                if a["claim"] != "-":
                    claims.append((name, a))
        print()
        dup = {k: v for k, v in seen.items() if len(v) > 1}
        if dup:
            print("  seed collisions (the same fight replayed): %s" % dup)
        print("  every Fight this arm played, (armed hands, revealed BP) "
              "-> landed hits:count")
        for k in sorted(ladder):
            h = ladder[k]
            print("    hands=%d bp=%d  %s" % (
                k[0], k[1], ",".join("%d:%d" % (v, h[v]) for v in sorted(h))))
        print()
        print("  every keyed claim, carried onto the action it was planned "
              "for (claim=<line>/<chips>/<shields>/breaks|best):")
        kept = missed = 0
        for name, a in claims:
            what, chips, need, kind = a["claim"].split("/")
            if kind != "breaks":
                continue                 # "the most the bank allows": no claim
            need = int(need[:-2])
            ok = a["sh1"] == 0 and a["sh0"] > 0
            # a claim is only judged against the gauge it was made about: an
            # ally acting in between can drop the gauge before this turn
            # resolves, and that is a different story from a wrong model
            if a["sh0"] != need:
                verdict = "STALE (gauge moved to %d before the turn resolved)" \
                    % a["sh0"]
            elif ok:
                verdict = "BROKE"
                kept += 1
            else:
                verdict = "DID NOT BREAK"
                missed += 1
            print("    %-11s t%-3d slot=%d %-14s claims %s chips on %d -> "
                  "%d landed hit(s), sh %d->%d  %s" % (
                      name, a["turn"], a["slot"], what.replace("_", " "),
                      chips[:-5], need, a["hits"], a["sh0"], a["sh1"],
                      verdict))
        print("    claims judged on the gauge they named -- kept: %d  "
              "BROKEN: %d" % (kept, missed))
        print()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", choices=["model", "write", "run", "aggregate"])
    ap.add_argument("arms", nargs="*")
    ap.add_argument("--seeds", default="0,7,13,19,27,34,41,53")
    ap.add_argument("--jobs", type=int, default=4)
    a = ap.parse_args()
    if a.cmd == "model":
        model_table()
        return 0
    if a.cmd == "write":
        print(write(a.arms[0] if a.arms else "arm", 0))
        return 0
    if a.cmd == "aggregate":
        arms = a.arms or [d for d in sorted(os.listdir(OUT))
                          if os.path.isdir(os.path.join(OUT, d))] \
            if os.path.isdir(OUT) else []
        aggregate(arms)
        return 0
    seeds = [int(x) for x in a.seeds.split(",") if x != ""]
    if not a.arms:
        sys.exit("run: name an arm (a directory label, e.g. before / after)")
    jobs = [(arm, s) for arm in a.arms for s in seeds]
    rcs = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=a.jobs) as ex:
        for arm, seed, rc, s in ex.map(lambda j: run_one(*j), jobs):
            res = s["result"] or {}
            print("%-8s shift=%-3d rc=%d %-5s seed=%-3s %s t=%s turns=%s "
                  "ifr=%s shv=%s %s" % (
                      arm, seed, rc, s["verdict"], res.get("seed", "??"),
                      res.get("outcome", "-"), res.get("t", "-"),
                      res.get("turns", "-"), res.get("ifr_break_turn", "-"),
                      res.get("shv_break_turn", "-"), s["fail"][:60]))
            sys.stdout.flush()
            rcs.append(rc)
    return 0


if __name__ == "__main__":
    sys.exit(main())
