#!/bin/sh
# run.sh <script.lua> [logfile] -- run a Lua test under Mesen 2's headless testrunner.
#
#   tools/tests/run.sh tools/tests/battle_smoke.lua
#
# * Composes the script with lib/ot6.lua into one flat file first
#   (build/states/_composed.lua).  Runtime dofile()/loadfile() raise under
#   Mesen's default AllowIoOsAccess=false setting (a raise at script load
#   registers no callbacks, so the run then dies on the wall-clock cap --
#   that is the "255 crash", not a crash).  Inlining keeps runs hermetic;
#   see compose.py.  A script that is
#   ALREADY composed (first line carries compose.py's marker) runs as-is --
#   suite.sh pre-composes every test once so a mid-suite lib edit can't split
#   a suite across two libs.
# * Runs build/ot6.sfc (rebuild with `make rom` if you changed sources).
# * All emulator/script output goes to the logfile
#   (default: build/states/last_run.log).
# * [b64:<tag>] payloads emitted by the script (savestates, screenshots) are
#   decoded into build/states/ and build/states/shots/ afterwards.
# * OT6_WORKER=<id> reroutes EVERYTHING the run touches -- portable app copy,
#   saves dir, composed file, default log, artifact decode dir -- under
#   build/test-workers/w<id>/, so runs with distinct ids (and the default,
#   id-less run) are safe concurrently.  Two workers must never share an app
#   copy: run.sh rewrites settings.json into the bundle every launch (so they
#   would race on each other's SaveDataFolder) and the emulator writes
#   Debugger/*.cdl there.  (It does NOT write settings back -- the testrunner
#   sets DisableSaveSettings -- and never creates SaveStates/.)
# * Exit code: 0 = pass, 1 = assertion/Lua error, 2 = frame budget exceeded.
#   The [ot6] PASS/FAIL verdict in the log wins over the raw process code
#   (a 255 with unflushed stdout is a wall-clock cap, not a crash).
set -u
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
ROM="$ROOT/build/ot6.sfc"
SCRIPT="${1:?usage: run.sh <script.lua> [logfile]}"

# Isolated portable Mesen for tests: the testrunner flushes battery saves
# on exit and twice zeroed the user's in-game save (ot6.srm) when sharing
# the real profile. A $HOME override is ignored on macOS, so tests run a
# portable copy (settings.json beside the binary = portable mode). We
# ALSO force an explicit SaveDataFolder override to a dedicated testing
# dir, so the user's save stays untouchable even if their settings later
# grow an override that would otherwise be inherited (the manual-play
# save and the repeatable-testing saves never share a directory).
if [ -n "${OT6_WORKER:-}" ]; then
  WDIR="$ROOT/build/test-workers/w$OT6_WORKER"
  MESEN_TEST="$WDIR/Mesen.app"
  TEST_SAVES="$WDIR/saves"
  COMPOSED="$WDIR/composed.lua"
  LOG="${2:-$WDIR/last_run.log}"
  ART="$WDIR/artifacts"
else
  MESEN_TEST="$ROOT/build/mesen-test.app"
  TEST_SAVES="$ROOT/build/mesen-test-saves"
  COMPOSED="$ROOT/build/states/_composed.lua"
  LOG="${2:-$ROOT/build/states/last_run.log}"
  ART="$ROOT/build/states"
fi
mkdir -p "$TEST_SAVES" "$ART/shots"

if head -n 1 "$SCRIPT" | grep -q '^-- AUTOGENERATED by lib/compose.py'; then
  COMPOSED="$SCRIPT"   # pre-composed by suite.sh; run as-is
else
  python3 "$ROOT/tools/tests/lib/compose.py" "$SCRIPT" "$COMPOSED" || exit 2
fi

# One-time portable emulator copy. cp -c = APFS clonefile: instant and ~zero
# physical disk; falls back to a plain copy on non-APFS filesystems.
if [ ! -x "$MESEN_TEST/Contents/MacOS/Mesen" ]; then
  echo "creating portable test emulator (one-time copy)..."
  rm -rf "$MESEN_TEST"
  cp -c -R "$ROOT/tools/Mesen.app" "$MESEN_TEST" 2>/dev/null || cp -R "$ROOT/tools/Mesen.app" "$MESEN_TEST"
fi
# (re)write the portable settings every run so the override can't drift
python3 "$ROOT/tools/tests/lib/pin_test_saves.py" \
  "$HOME/Library/Application Support/Mesen2/settings.json" \
  "$MESEN_TEST/Contents/MacOS/settings.json" \
  "$TEST_SAVES"

# Fresh battery every run: the testrunner flushes SRAM to <saves>/*.srm on
# exit and silently reloads it next boot -- a stale srm is a hidden
# cross-run coupling channel (and fossilizes into minted savestates).
# Tests that need a save inject it explicitly (SRM sidecars).
rm -f "$TEST_SAVES"/*.srm
# --timeout=600: Mesen's testrunner has a hard DEFAULT 100-second wall-clock
# cap (exit -1/255 + truncated stdout on expiry) that reaped long runs; keep
# a cap as the only defense against a genuinely hung emulator, just a roomy one.
# --enableStdout mirrors the EMULATOR message log to stdout.  It does NOT
# carry Lua errors or watchdog kills -- those go to the script log, which
# nothing reads headless.  A script that goes quiet has told you nothing;
# print() is the only channel out.  Kept for the ROM-info banner.
"$MESEN_TEST/Contents/MacOS/Mesen" --testrunner --timeout=600 --enableStdout "$ROM" "$COMPOSED" > "$LOG" 2>&1
code=$?

python3 "$ROOT/tools/tests/lib/decode_b64.py" "$LOG" "$ART"
grep '^\[ot6\]' "$LOG"

if grep -q '^\[ot6\] PASS' "$LOG"; then
  verdict=0
elif grep -q '^\[ot6\] FAIL' "$LOG"; then
  verdict=1
else
  verdict=$code
fi
echo "testrunner exit: $code (verdict: $verdict)"
exit "$verdict"
