#!/usr/bin/env python3
"""Compose a self-contained Lua test file for Mesen's testrunner.

Why: runtime dofile()/loadfile() RAISE under Mesen's default setting
Debug.ScriptWindow.AllowIoOsAccess=false (Lua/lauxlib.c:776) -- the error is
clean and names the setting, but an unguarded dofile at script load means no
callbacks ever register, the emulator free-runs, and the testrunner's
wall-clock cap reaps it as exit 255.  That signature is what an earlier note
here called "intermittent emulator crashes"; it was neither intermittent nor
a crash.

Flipping that setting would make runtime loading work.  We do not, and
inline instead: one flat file is hermetic, which is worth more to a
reproducible suite than the convenience.  So this script textually inlines
the test library -- BOTH halves: lib/ot6.lua (battle core) and
lib/ot6_field.lua (field/world navigation) -- and any savestate sidecars the
script references, into one file with no runtime file access at all.

Transformations:
  1. The line `local H = dofile(".../lib/ot6.lua")` is replaced by the two
     lib halves; see inline_libs() for the exact shape.  Every script gets
     both, always -- a battle test carries nav code it never calls, which
     costs composed-file bytes and nothing else, and keeps this step free
     of script-inspection cleverness.
  2. For every `H.loadState("<path>.mss.lua")` reference whose sidecar file
     exists, the sidecar's base64 payload is embedded into a global table
     `OT6_STATES[basename]`; the lib's loadState() checks that table first,
     so no loadfile() happens at runtime.  The sidecar is taken from THIS
     tree's build/states whenever it has one -- see the precedence table at
     the resolution loop -- and every embedded state is named, with a short
     hash, in a comment and a print() at the head of the composed file.

Usage: compose.py <script.lua> <out.lua>

SCENARIO STACKING (OT6_STACK): the v0.3 scenario routes each replay one
branch of the SAME three-way split, and the reunion gate (_caadb9,
event_main.asm:26683) needs all three completed in ONE playthrough.  The
route generators hardcode both their boot sidecar ("scenario_hub.mss.lua")
and their output names ("rapids_done.mss"), so replaying a route from
another scenario's endpoint used to mean either duplicating a 600-line
generator or clobbering the honest single-scenario states.  Instead:
`OT6_STACK=<prefix>` makes composition rewrite the BASENAME of every
`.mss`/`.mss.lua` string literal in the SCRIPT (never the lib), so
`OT6_STACK=t2_` composes gen_rapids into a script that boots
t2_scenario_hub.mss.lua and emits t2_rapids_*.mss.  The Makefile seeds
t2_scenario_hub as a copy of locke_done, and the whole Terra chain then
replays on top of the Locke ending -- same route logic, different boot,
distinct artifacts.  This lives at compose time because that is where
sidecar literals are already resolved (the tree-precedence rules above);
the generators stay byte-identical, and the re-mint gate keeps working
because stacked artifacts are ordinary files on the same .rom-copy clock.
"""
import hashlib
import os
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
LIB = HERE / "ot6.lua"            # battle core; yields the module table
FIELD = HERE / "ot6_field.lua"    # nav half; installs onto that same table
FRONTIER_STAMP = HERE / "frontier_stamp.sh"  # the ONE definition of the mint sig
ROOT = HERE.parent.parent.parent           # lib/ -> tests/ -> tools/ -> tree root
MARKER = "-- AUTOGENERATED by lib/compose.py; edit the source script instead."
# The ca65 debug file for THIS tree's ROM.  A whole family of tests used to
# hardcode absolute bank-$F0 (OT6 data tables) / $C2 (battle) / $C0 (RNG)
# addresses that SHIFT on any code/data growth, so each went stale on every
# bank edit -- the single most recurring source of harness breakage.  We
# derive them here instead: any symbol a script names via H.sym("Name") is
# looked up in this file and injected as OT6_SYMS, the same mechanism
# OT6_STATES uses for savestate sidecars.  Built by `make rom`; a test that
# needs a symbol before the ROM is built fails loudly at H.sym (see ot6.lua).
DBG = ROOT / "ff6" / "rom" / "ff6-en.dbg"


def payload(sidecar: Path) -> str:
    """The base64 blob out of a `return "<b64>"` sidecar ("" if malformed)."""
    m = re.search(r'return\s+"([A-Za-z0-9+/=]+)"', sidecar.read_text())
    return m.group(1) if m else ""


def digest(b64: str) -> str:
    """Short fingerprint of an embedded payload, for the provenance lines.

    Hashes the base64 TEXT rather than the sidecar file, so it ignores the
    `return "..."` wrapper and can be recomputed from either side of a
    mismatch -- a composed file or a sidecar.  `compose.py --sha <sidecar>`
    prints it, so the hash in a run log is checkable against a local state
    instead of being a number nobody can reproduce.
    """
    return hashlib.sha256(b64.encode()).hexdigest()[:12]


def mint_sig(gen, root, extras=()):
    """The sha256(generator ++ lib/ot6.lua ++ lib/ot6_field.lua), from the
    ONE authority.

    A minted fixture's freshness stamp is compared on two sides -- the mint
    gate (lib/frontier_stamp.sh, shell) writes it, this consume-time check
    (below) re-derives it -- and the two MUST agree byte-for-byte or the guard
    silently passes stale fixtures.  So rather than reimplement the digest here
    (`cat gen lib | shasum`, an independent copy that could drift), we shell out
    to the gate's own `sig` subcommand: its 64-hex prefix IS the definition.
    OT6_ROOT points the gate at the composing tree, so it reads exactly the
    gen/lib bytes this side would have.  compose runs once per test, so the
    subprocess cost is negligible next to the emulator run it precedes.
    """
    out = subprocess.run(
        ["sh", str(FRONTIER_STAMP), "sig", gen, *extras],
        env={**os.environ, "OT6_ROOT": str(root)},
        capture_output=True, text=True, check=True,
    ).stdout
    return out.split()[0]            # "<64-hex> <gen>" -> the digest half


def stamp_check(name, root):
    """Consume-time half of the issue #2 freshness gate.

    The mint-time gate (Makefile + lib/frontier_stamp.sh) re-mints a frontier
    fixture when its generator or either lib half changes -- but only when
    `make frontier` runs.  A fixture can still reach a test WITHOUT that: the
    suite adds a frontier-gated test the moment its .mss exists, and
    `make test` never builds the frontier, so a state that worktree-setup
    seeded from another tree (and a local generator edit has since drifted)
    would be embedded and asserted on silently.  The mint records
    `<sha256(generator++lib)> <generator>` in build/states/<base>.stamp; here we
    recompute it for the fixture we are about to embed and, on a mismatch,
    return a loud line the composed file prints through the [ot6] channel.

    Returns None when there is nothing to check -- no stamp (the suite's own
    states, the stack seeds, or a fixture minted before this gate existed) or a
    generator that has since been removed -- so it never invents a warning.
    """
    base = name[:-len(".mss.lua")] if name.endswith(".mss.lua") else name
    stamp = root / "build" / "states" / (base + ".stamp")
    if not stamp.exists():
        return None
    parts = stamp.read_text().split()
    if len(parts) < 2:
        return None
    recorded, gen, *extras = parts
    gen_lua = root / "tools" / "tests" / (gen + ".lua")
    if not gen_lua.exists():
        return None
    cur = mint_sig(gen, root, extras)
    if cur == recorded[:64]:
        return None
    return (f"fixture {base} is STALE -- minted from {gen}+lib "
            f"sha {recorded[:12]}, current script hashes {cur[:12]}; "
            f"re-run `make frontier` to refresh it (issue #2)")


class CrossTree(Exception):
    """A referenced sidecar exists ONLY outside the composing tree."""


def inline_libs(script: str, lib: str, field: str):
    """Swap the script's `local H = dofile(".../lib/ot6.lua")` line for both
    lib halves, inlined:

        local H = (function()
        <lib/ot6.lua>              -- ends with `return M`
        end)()
        ;(function(...)
        <lib/ot6_field.lua>        -- first line `local M = ...` binds H
        end)(H)

    The core composes exactly as it always did -- wrapped in a function so
    its `return M` yields the module, bound to the script's H.  The field
    half is a SECOND chunk in the same file, invoked immediately with H as
    its argument, so it installs navTo/bfsPath/worldNavTo/... onto the very
    table the script already holds; the two-scope shape keeps each source
    file an honest Lua chunk on its own (no cross-file locals -- the one
    core local the field half needs, seqStep, is exported on M).  The
    leading `;` is load-bearing: without it Lua reads `(function...` as a
    call on the previous line's value, not a new statement.

    Returns (composed_text, replaced); replaced False means the script never
    dofiles the lib (smoke.lua) and the text came through untouched.
    """
    out, replaced = [], False
    for line in script.splitlines(keepends=True):
        if not replaced and "dofile(" in line and "lib/ot6.lua" in line:
            out.append("local H = (function()\n")
            out.append(lib)
            out.append("\nend)()\n")
            out.append(";(function(...)\n")
            out.append(field)
            out.append("\nend)(H)\n")
            replaced = True
        else:
            out.append(line)
    return "".join(out), replaced


# Any .mss / .mss.lua string literal: group 1 = directory part (kept),
# group 2 = the basename the stack prefix goes onto.
_MSS_LIT = re.compile(r'"((?:[^"]*/)?)([A-Za-z0-9_]+\.mss(?:\.lua)?)"')

# Any H.sym("Name") / M.sym('Name') / sym("Name") reference: group 1 is the
# ca65 symbol name to resolve out of ff6-en.dbg.  Matches only `sym(` at a
# word boundary, so `foo.symbolic(...)` is not a false positive.  Names found
# in comments over-collect harmlessly (an extra OT6_SYMS entry is inert).
_SYM_REF = re.compile(r'\bsym\s*\(\s*["\']([A-Za-z_][A-Za-z0-9_]*)["\']')


def parse_dbg_syms(dbg, wanted):
    """name -> integer address for each `wanted` ca65 symbol found in `dbg`.

    The .dbg carries one record per line; a `.proc`/label emits several with
    the same name (a `scope`, an `imp` import, and the `lab` definition), but
    only the `type=lab` record carries `val=0x...` -- the address we want.  So
    we consider label lines only and take the first `val` for each name; a
    name with no label record simply does not appear in the result, and
    H.sym() raises for it at runtime (the same loud failure as a missing
    savestate sidecar).  Returns {} when nothing is wanted or the .dbg is
    absent (an unbuilt ROM) -- again deferring the loud failure to H.sym.
    """
    out = {}
    wanted = list(dict.fromkeys(wanted))
    if not wanted or not dbg.exists():
        return out
    markers = {'name="%s"' % w: w for w in wanted}
    val_re = re.compile(r'\bval=0x([0-9A-Fa-f]+)')
    with dbg.open() as f:
        for line in f:
            if "type=lab" not in line:
                continue
            for mk, name in markers.items():
                if name in out:
                    continue
                if mk in line:
                    m = val_re.search(line)
                    if m:
                        out[name] = int(m.group(1), 16)
                    break
            if len(out) == len(wanted):
                break
    return out


def stack_rewrite(script: str, prefix: str) -> str:
    """Prefix the basename of every .mss/.mss.lua literal in `script`.

    Both directions must move together: prefixing only loadState references
    would boot gen_rapids from t2_scenario_hub and then let it OVERWRITE the
    honest rapids_start/rapids_done with states minted from a contaminated
    boot -- the exact silent-wrong-artifact class the resolver selftest
    exists for.  Screenshot tags carry no .mss suffix and are untouched;
    comments mentioning state names get rewritten too, which is harmless.
    """
    if not prefix:
        return script
    if not re.fullmatch(r"[A-Za-z0-9_]+", prefix):
        raise ValueError(f"OT6_STACK={prefix!r}: prefix must be [A-Za-z0-9_]+")
    return _MSS_LIT.sub(lambda m: f'"{m.group(1)}{prefix}{m.group(2)}"', script)


def resolve_sidecar(ref, root):
    """Pick the sidecar file a "<path>.mss.lua" reference should embed.

    Every test writes tree-relative references ("build/states/x.mss.lua") --
    the last absolute literals (the gen_*.lua's) migrated in the remint
    window that followed issue #26, so an ABSOLUTE reference is now refused
    outright rather than resolved.  That makes the whole #26 class
    structural: an absolute path is how a test comes to mean "some other
    tree's bytes", and the eleven stale-worktree literals that motivated
    the issue could not have been written under this rule.  Composition is
    already tree-local everywhere else: LIB ignores the script's literal
    dofile path in exactly the same way.

    Precedence, per reference:
      0. an absolute literal -> raise CrossTree, always -- even one naming
         this very tree, which would only mean "works until the tree moves"
      1. <root>/build/states/<basename>       -- always wins if present
      2. the literal anchored at <root> (never the composer's cwd, which
         would make resolution depend on where make/run.sh was invoked)
      3. the anchored literal escapes <root> (via ..) or crosses into a
         NESTED git tree inside <root> (an agent worktree under
         .claude/worktrees/ sits inside the main tree on disk but is a
         different checkout with a different ROM) -> raise CrossTree
      4. nowhere -> None; embed nothing, the lib raises "sidecar not
         embedded" at loadState, which is already a clear failure

    Rule 1 is the fix.  An earlier pass consulted this tree only when the
    literal MISSED -- but the literal (a main-tree path) essentially always
    exists, so the fallback never fired, and a worktree that had legitimately
    re-minted a state for its own modified ROM still composed the MAIN
    tree's stale copy.

    Rule 3 refuses rather than silently borrowing.  A foreign tree's state
    was minted from a DIFFERENT ROM, so a run against it is a green that
    proves nothing; and reading it while that tree re-mints is a cross-tree
    race besides.  run.sh already takes this line for the settings pin
    ("Refusing the run beats reporting a green that never had the pins") --
    a fixture is no weaker a guarantee than a settings file.

    Rule 0 subsumes what the nested-worktree check used to be the last line
    of defense for (issue #26: eleven tests authored inside
    .claude/worktrees/agent-a7ce... kept that tree's absolute paths, which
    passed is_relative_to(root) and silently borrowed the other checkout's
    fixture).  The nested-.git check stays: a RELATIVE path can still be
    spelled through a nested checkout, and refusing it must not depend on
    how the reference was written.
    """
    literal = Path(ref)
    if literal.is_absolute():
        raise CrossTree(f"{ref} -- absolute sidecar reference; "
                        f"write it tree-relative (build/states/...)")
    local = root / "build" / "states" / literal.name
    if local.exists():
        return local
    literal = root / literal
    if literal.exists():
        resolved = literal.resolve()
        if not resolved.is_relative_to(root):
            raise CrossTree(ref)
        # Inside root, but crossing into a nested checkout?  A git worktree
        # (or submodule) marks its own top with a .git entry -- a FILE for
        # worktrees, a directory for a clone -- so any .git between the
        # literal and root means the file belongs to a different tree.
        for parent in resolved.parents:
            if parent == root:
                break
            if (parent / ".git").exists():
                raise CrossTree(ref)
        return literal
    return None


def selftest() -> int:
    """Positive control for resolve_sidecar's precedence: `compose.py --selftest`.

    The bug this guards is a SILENT wrong answer -- composition that quietly
    embeds another tree's savestate -- so asserting "it composed fine" would
    itself pass for the wrong reason.  Each case below therefore pins WHICH
    file was chosen, and case 1 (the regression) is built so that the old
    literal-first code would have picked the other one.
    """
    import tempfile

    ok = True

    def check(label, got, want):
        nonlocal ok
        if got != want:
            ok = False
            print(f"  FAIL {label}\n       got  {got}\n       want {want}")
        else:
            print(f"  pass {label}")

    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp).resolve()
        main_tree, work = tmp / "ot6", tmp / "ot6" / ".claude" / "wt" / "a"
        for t in (main_tree, work):
            (t / "build" / "states").mkdir(parents=True)
        # A worktree nests INSIDE the main tree on disk, as real ones do --
        # so "outside this tree" cannot be a naive prefix test in reverse.
        m_state = main_tree / "build" / "states" / "s.mss.lua"
        w_state = work / "build" / "states" / "s.mss.lua"
        m_state.write_text('return "TUFJTg=="\n')
        w_state.write_text('return "V09SSw=="\n')

        def refused(label, ref, tree):
            try:
                got = resolve_sidecar(ref, tree)
                check(label, f"returned {got}", "CrossTree")
            except CrossTree:
                check(label, "CrossTree", "CrossTree")

        # 0. RULE 0: an absolute reference is refused no matter whose tree
        # it names -- including the composing tree's own path.  The pre-#26
        # regression (a worktree composing the main tree's hardcoded path)
        # is now unreachable by construction rather than out-resolved.
        refused("absolute ref refused even naming the composing tree",
                str(w_state), work)
        refused("absolute ref into another tree refused", str(m_state), work)
        # 1. This tree's build/states wins on basename, wherever the
        # relative literal points.
        check("local basename copy beats the literal's location",
              resolve_sidecar("fixtures/s.mss.lua", work), w_state)
        # 2. A relative literal anchors at the composing tree's root, never
        # the composer's cwd (which belongs to whoever invoked make).
        odd = work / "fixtures"
        odd.mkdir()
        (odd / "x.mss.lua").write_text('return "WA=="\n')
        check("relative literal resolves against the tree root",
              resolve_sidecar("fixtures/x.mss.lua", work), odd / "x.mss.lua")
        # 3a. Escaping the tree via .. is refused, not resolved.
        (tmp / "outside.mss.lua").write_text('return "T1VU"\n')
        refused("dot-dot escape refused", "../../../../outside.mss.lua", work)
        # 3b. THE ISSUE #26 HOLE, relative form: a reference spelled
        # through a NESTED worktree stays inside root but names a different
        # checkout minted from a different ROM.  (A worktree's top carries
        # .git as a FILE; model that exactly.)
        nested = main_tree / ".claude" / "worktrees" / "agent-b"
        (nested / "build" / "states").mkdir(parents=True)
        (nested / ".git").write_text("gitdir: /somewhere/else\n")
        n_state = nested / "build" / "states" / "nested_only.mss.lua"
        n_state.write_text('return "TkVTVA=="\n')
        refused("nested-worktree reference refused",
                ".claude/worktrees/agent-b/build/states/nested_only.mss.lua",
                main_tree)
        # 4. Missing everywhere -> None (the lib raises at loadState).
        check("absent everywhere yields None",
              resolve_sidecar("build/states/nope.mss.lua", work), None)

    # -- stack_rewrite: both directions of a route must move together --
    src = ('local HUB = "/Users/x/ot6/build/states/scenario_hub.mss.lua"\n'
           'H.saveState("rapids_done.mss")\n'
           'H.screenshot("rapids_battle1")\n')
    got = stack_rewrite(src, "t2_")
    check("stack prefixes the boot sidecar reference",
          '"/Users/x/ot6/build/states/t2_scenario_hub.mss.lua"' in got, True)
    check("stack prefixes the emitted state name",
          'H.saveState("t2_rapids_done.mss")' in got, True)
    check("stack leaves screenshot tags alone",
          'H.screenshot("rapids_battle1")' in got, True)
    check("empty prefix is the identity", stack_rewrite(src, ""), src)
    try:
        stack_rewrite(src, "bad/../prefix")
        check("stack refuses a non-word prefix", "no raise", "ValueError")
    except ValueError:
        check("stack refuses a non-word prefix", "ValueError", "ValueError")

    # -- inline_libs: both halves ride along, and the field half is fed H --
    lib_src = "-- core\nlocal M = {}\nCOREBODY\nreturn M"
    field_src = "-- field\nlocal M = ...\nFIELDBODY"
    script_src = ("-- a test\n"
                  'local H = dofile("/Users/x/ot6/tools/tests/lib/ot6.lua")\n'
                  "H.run({}, {})\n")
    got, replaced = inline_libs(script_src, lib_src, field_src)
    check("inline replaces the dofile line", replaced, True)
    check("inline drops the dofile call itself", "dofile(" not in got, True)
    check("inline binds the core to H", "local H = (function()" in got, True)
    check("inline appends the field half after the core",
          -1 < got.find("COREBODY") < got.find("FIELDBODY"), True)
    check("inline starts the field chunk as a new statement (the ';')",
          ";(function(...)" in got, True)
    check("inline hands the field chunk H", "end)(H)" in got, True)
    check("inline leaves the rest of the script alone",
          got.startswith("-- a test\n") and got.endswith("H.run({}, {})\n"),
          True)
    got2, replaced2 = inline_libs("print('no lib')\n", lib_src, field_src)
    check("no lib reference -> untouched, unreplaced",
          (got2, replaced2), ("print('no lib')\n", False))
    # the wrapper's two load-bearing assumptions about the REAL lib files:
    check("lib/ot6.lua ends by returning its module table",
          LIB.read_text().rstrip().endswith("return M"), True)
    check("lib/ot6_field.lua opens by receiving that table (local M = ...)",
          any(l.strip() == "local M = ..."
              for l in FIELD.read_text().splitlines()[:40]), True)

    # -- _SYM_REF: collect H.sym/M.sym names, ignore look-alikes and dupes --
    refs = _SYM_REF.findall(
        'local R = H.sym("RandA")\n'
        "local S = M.sym('Ot6ShieldTbl')\n"
        'local R2 = H.sym("RandA")\n'          # a repeat: dedup is the caller's
        '-- a name in a comment: sym("InComment")\n'
        'foo.symbolic("NotASym"); local t = symtab["NotASym"]\n')
    check("sym refs collect real calls (with the comment name, harmlessly)",
          refs, ["RandA", "Ot6ShieldTbl", "RandA", "InComment"])
    check("sym refs ignore symbolic()/symtab[] look-alikes",
          "NotASym" not in refs, True)

    # -- parse_dbg_syms: the type=lab record's val wins; scope/imp are skipped;
    #    an unknown name is simply absent (H.sym raises for it at runtime) --
    with tempfile.TemporaryDirectory() as tmp:
        dbg = Path(tmp) / "ff6-en.dbg"
        dbg.write_text(
            'scope\tid=1,name="RandA",mod=2,type=scope,size=4\n'
            'sym\tid=2,name="RandA",addrsize=absolute,def=9,type=imp,exp=2\n'
            'sym\tid=3,name="RandA",scope=1700,def=9,val=0xC24B98,seg=52,type=lab\n'
            'sym\tid=4,name="Ot6ShieldTbl",scope=1700,val=0xF01050,seg=67,type=lab\n'
            'sym\tid=5,name="Decoy",scope=0,val=0xDEAD00,seg=1,type=equ\n')
        got = parse_dbg_syms(dbg, ["RandA", "Ot6ShieldTbl", "Missing", "Decoy"])
        check("parse picks the type=lab val over scope/imp",
              got.get("RandA"), 0xC24B98)
        check("parse resolves a second wanted label",
              got.get("Ot6ShieldTbl"), 0xF01050)
        check("parse omits an unknown name", "Missing" in got, False)
        check("parse omits a non-lab (type=equ) record", "Decoy" in got, False)
        check("parse of an absent .dbg is empty (defers to H.sym)",
              parse_dbg_syms(Path(tmp) / "nope.dbg", ["RandA"]), {})
        check("parse of no wanted names is empty (inert injection)",
              parse_dbg_syms(dbg, []), {})

    print("selftest: " + ("ok" if ok else "FAILED"))
    return 0 if ok else 1


def main() -> int:
    if len(sys.argv) == 2 and sys.argv[1] == "--selftest":
        return selftest()
    # --sha <sidecar>: the same fingerprint the provenance lines carry, so a
    # hash seen in a run log can be checked against a state on disk.
    if len(sys.argv) == 3 and sys.argv[1] == "--sha":
        print(digest(payload(Path(sys.argv[2]))))
        return 0
    script_path, out_path = Path(sys.argv[1]), Path(sys.argv[2])
    script = script_path.read_text()
    lib = LIB.read_text()

    # Composing is NOT idempotent (the usage-example dofile line in the
    # inlined lib header would re-trigger inlining), so refuse re-composition.
    # run.sh runs already-composed files (first line = MARKER) directly.
    if script.startswith(MARKER):
        print(f"error: {script_path} is already composed; refusing to re-compose")
        return 1

    # Scenario stacking: rewrite state basenames BEFORE sidecar collection,
    # so the resolver sees (and embeds) the prefixed names.  Script only --
    # the lib's own .mss mentions are documentation, and rewriting the lib
    # would make the composed lib differ per prefix for no behavioral reason.
    stack = os.environ.get("OT6_STACK", "")
    if stack:
        script = stack_rewrite(script, stack)
        print(f"stack prefix {stack!r} applied to {script_path}")

    # Collect referenced savestate sidecars: any "<path>.mss.lua" string
    # literal in the script (scripts typically bind them to a STATE local).
    # resolve_sidecar() owns the precedence; see its docstring.
    states, sources = {}, {}
    for ref in dict.fromkeys(re.findall(r'"([^"]+\.mss\.lua)"', script)):
        try:
            p = resolve_sidecar(ref, ROOT)
        except CrossTree:
            print(f"error: {script_path} references {ref}, which exists only "
                  f"OUTSIDE this tree ({ROOT}).  Refusing to compose another "
                  f"tree's savestate: it was minted from a different ROM, so "
                  f"a run against it proves nothing.  Mint it here (make, or "
                  f"the generator that emits it), or seed this tree with "
                  f"tools/worktree-setup.sh.")
            return 1
        if p is None:
            continue
        b64 = payload(p)
        if b64:
            states[Path(ref).name], sources[Path(ref).name] = b64, p

    # Say WHICH sidecar got embedded, in the composed file itself.  A state
    # mismatch otherwise looks like a ROM bug: the run loads a fixture that
    # is subtly wrong and fails somewhere unrelated, with nothing anywhere
    # naming the file it actually came from.  The print() lands in the run
    # log (run.sh greps '^[ot6]', so it reaches the terminal too) and the
    # comment survives in the composed artifact for later inspection.
    preamble = [MARKER + "\n"]
    if states:
        for name, b64 in states.items():
            preamble.append(f"-- state {name} sha={digest(b64)} "
                            f"({len(b64)} b64 chars) <- {sources[name]}\n")
        preamble.append("OT6_STATES = {\n")
        for name, b64 in states.items():
            preamble.append(f'  ["{name}"] = "{b64}",\n')
        preamble.append("}\n")
        for name, b64 in states.items():
            preamble.append(f'print("[ot6] state {name} sha={digest(b64)} '
                            f'<- {sources[name]}")\n')
        # issue #2: warn LOUDLY if an embedded fixture no longer matches the
        # generator+lib it was minted from (a drift the mint gate refreshes only
        # under `make frontier`, which `make test` never runs).  Non-fatal: the
        # print lands in the [ot6] log run.sh and suite.sh both surface.
        for name in states:
            stale = stamp_check(name, ROOT)
            if stale:
                preamble.append(f"-- WARNING (issue #2): {stale}\n")
                preamble.append(f'print("[ot6] WARNING: {stale}")\n')
                print(f"WARNING: {stale}")

    # OT6 symbol addresses: derive them from THIS TREE's ff6-en.dbg the same
    # way OT6_STATES embeds sidecars.  Only symbols the SCRIPT names via
    # H.sym("...") are collected, so the injection is INERT for every test
    # that does not use it (no reference -> no table emitted).  See ot6.lua
    # M.sym for the accessor and the loud error on a missing symbol.
    sym_names = list(dict.fromkeys(_SYM_REF.findall(script)))
    if sym_names:
        syms = parse_dbg_syms(DBG, sym_names)
        preamble.append(f"-- OT6 symbols from {DBG} (via lib/compose.py)\n")
        preamble.append("OT6_SYMS = {\n")
        for name in sym_names:
            if name in syms:
                preamble.append(f'  ["{name}"] = 0x{syms[name]:06X},\n')
        preamble.append("}\n")
        # A named-but-unresolved symbol is a loud, non-fatal warning here; the
        # actual failure is H.sym raising at runtime (an unbuilt ROM, or a
        # typo'd name).  Matches how a missing sidecar defers to loadState.
        for name in sym_names:
            if name not in syms:
                msg = (f"symbol {name} not found in ff6/rom/ff6-en.dbg "
                       f"-- rebuild the ROM, or check the name")
                preamble.append(f'print("[ot6] WARNING: {msg}")\n')
                print(f"WARNING: {msg}")

    composed, replaced = inline_libs(script, lib, FIELD.read_text())
    if not replaced:
        # script doesn't use the lib (e.g. smoke.lua); pass it through, marked
        out_path.write_text(MARKER + "\n" + script)
        print(f"composed {out_path} (no lib reference; copied as-is)")
        return 0

    out_path.write_text("".join(preamble) + composed)
    print(f"composed {out_path} ({len(states)} embedded savestate(s))")
    for name, b64 in states.items():
        print(f"  {name} sha={digest(b64)} <- {sources[name]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
