#!/usr/bin/env python3
"""Compose a self-contained Lua test file for Mesen's testrunner.

Why: runtime dofile()/loadfile() RAISE under Mesen's default setting
Debug.ScriptWindow.AllowIoOsAccess=false (Lua/lauxlib.c:776) -- the error is
clean and names the setting, but an unguarded dofile at script load means no
callbacks ever register, the emulator free-runs, and the testrunner's
wall-clock cap reaps it as exit 255.  That signature is what an earlier note
here called "intermittent emulator crashes"; it was neither intermittent nor
a crash.

Flipping that setting would make runtime loading work.  We do not, and
inline instead: one flat file is hermetic, which is worth more to a
reproducible suite than the convenience.  So this script textually inlines
lib/ot6.lua (and any savestate sidecars the script references) into one file
with no runtime file access at all.

Transformations:
  1. The line `local H = dofile(".../lib/ot6.lua")` is replaced by the lib
     source wrapped in `(function() ... end)()`.
  2. For every `H.loadState("<path>.mss.lua")` reference whose sidecar file
     exists, the sidecar's base64 payload is embedded into a global table
     `OT6_STATES[basename]`; the lib's loadState() checks that table first,
     so no loadfile() happens at runtime.

Usage: compose.py <script.lua> <out.lua>
"""
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
LIB = HERE / "ot6.lua"
MARKER = "-- AUTOGENERATED by lib/compose.py; edit the source script instead."


def main() -> int:
    script_path, out_path = Path(sys.argv[1]), Path(sys.argv[2])
    script = script_path.read_text()
    lib = LIB.read_text()

    # Composing is NOT idempotent (the usage-example dofile line in the
    # inlined lib header would re-trigger inlining), so refuse re-composition.
    # run.sh runs already-composed files (first line = MARKER) directly.
    if script.startswith(MARKER):
        print(f"error: {script_path} is already composed; refusing to re-compose")
        return 1

    # collect referenced savestate sidecars: any "<path>.mss.lua" string
    # literal in the script (scripts typically bind them to a STATE local).
    # Scripts hardcode the MAIN tree's absolute path (Mesen's sandbox has no
    # cwd, so the reference must be a fixed string) -- which strands git
    # worktrees: a state regenerated there lands in the WORKTREE's
    # build/states, the main-tree path doesn't exist, and composition
    # silently embeds nothing (the run then fails at loadState).  So resolve
    # each miss against this tree's own build/states (lib/ -> tests/ ->
    # tools/ -> root) before giving up; the lib looks states up by basename
    # (resolveStateB64), so where the sidecar was found doesn't matter.
    states = {}
    for ref in re.findall(r'"([^"]+\.mss\.lua)"', script):
        p = Path(ref)
        if not p.exists():
            p = HERE.parent.parent.parent / "build" / "states" / p.name
        if p.exists():
            content = p.read_text()
            m = re.search(r'return\s+"([A-Za-z0-9+/=]+)"', content)
            if m:
                states[p.name] = m.group(1)

    preamble = [MARKER + "\n"]
    if states:
        preamble.append("OT6_STATES = {\n")
        for name, b64 in states.items():
            preamble.append(f'  ["{name}"] = "{b64}",\n')
        preamble.append("}\n")

    out, replaced = list(preamble), False
    for line in script.splitlines(keepends=True):
        if not replaced and "dofile(" in line and "lib/ot6.lua" in line:
            out.append("local H = (function()\n")
            out.append(lib)
            out.append("\nend)()\n")
            replaced = True
        else:
            out.append(line)
    if not replaced:
        # script doesn't use the lib (e.g. smoke.lua); pass it through, marked
        out_path.write_text(MARKER + "\n" + script)
        print(f"composed {out_path} (no lib reference; copied as-is)")
        return 0

    out_path.write_text("".join(out))
    print(f"composed {out_path} ({len(states)} embedded savestate(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
