#!/usr/bin/env python3
"""Compose a self-contained Lua test file for Mesen's testrunner.

Why: runtime dofile()/loadfile() RAISE under Mesen's default setting
Debug.ScriptWindow.AllowIoOsAccess=false (Lua/lauxlib.c:776) -- the error is
clean and names the setting, but an unguarded dofile at script load means no
callbacks ever register, the emulator free-runs, and the testrunner's
wall-clock cap reaps it as exit 255.  That signature is what an earlier note
here called "intermittent emulator crashes"; it was neither intermittent nor
a crash.

Flipping that setting would make runtime loading work.  We do not, and
inline instead: one flat file is hermetic, which is worth more to a
reproducible suite than the convenience.  So this script textually inlines
lib/ot6.lua (and any savestate sidecars the script references) into one file
with no runtime file access at all.

Transformations:
  1. The line `local H = dofile(".../lib/ot6.lua")` is replaced by the lib
     source wrapped in `(function() ... end)()`.
  2. For every `H.loadState("<path>.mss.lua")` reference whose sidecar file
     exists, the sidecar's base64 payload is embedded into a global table
     `OT6_STATES[basename]`; the lib's loadState() checks that table first,
     so no loadfile() happens at runtime.  The sidecar is taken from THIS
     tree's build/states whenever it has one -- see the precedence table at
     the resolution loop -- and every embedded state is named, with a short
     hash, in a comment and a print() at the head of the composed file.

Usage: compose.py <script.lua> <out.lua>

SCENARIO STACKING (OT6_STACK): the v0.3 scenario routes each replay one
branch of the SAME three-way split, and the reunion gate (_caadb9,
event_main.asm:26683) needs all three completed in ONE playthrough.  The
route generators hardcode both their boot sidecar ("scenario_hub.mss.lua")
and their output names ("rapids_done.mss"), so replaying a route from
another scenario's endpoint used to mean either duplicating a 600-line
generator or clobbering the honest single-scenario states.  Instead:
`OT6_STACK=<prefix>` makes composition rewrite the BASENAME of every
`.mss`/`.mss.lua` string literal in the SCRIPT (never the lib), so
`OT6_STACK=t2_` composes gen_rapids into a script that boots
t2_scenario_hub.mss.lua and emits t2_rapids_*.mss.  The Makefile seeds
t2_scenario_hub as a copy of locke_done, and the whole Terra chain then
replays on top of the Locke ending -- same route logic, different boot,
distinct artifacts.  This lives at compose time because that is where
sidecar literals are already resolved (the tree-precedence rules above);
the generators stay byte-identical, and the re-mint gate keeps working
because stacked artifacts are ordinary files on the same .rom-copy clock.
"""
import hashlib
import os
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
LIB = HERE / "ot6.lua"
ROOT = HERE.parent.parent.parent           # lib/ -> tests/ -> tools/ -> tree root
MARKER = "-- AUTOGENERATED by lib/compose.py; edit the source script instead."


def payload(sidecar: Path) -> str:
    """The base64 blob out of a `return "<b64>"` sidecar ("" if malformed)."""
    m = re.search(r'return\s+"([A-Za-z0-9+/=]+)"', sidecar.read_text())
    return m.group(1) if m else ""


def digest(b64: str) -> str:
    """Short fingerprint of an embedded payload, for the provenance lines.

    Hashes the base64 TEXT rather than the sidecar file, so it ignores the
    `return "..."` wrapper and can be recomputed from either side of a
    mismatch -- a composed file or a sidecar.  `compose.py --sha <sidecar>`
    prints it, so the hash in a run log is checkable against a local state
    instead of being a number nobody can reproduce.
    """
    return hashlib.sha256(b64.encode()).hexdigest()[:12]


class CrossTree(Exception):
    """A referenced sidecar exists ONLY outside the composing tree."""


# Any .mss / .mss.lua string literal: group 1 = directory part (kept),
# group 2 = the basename the stack prefix goes onto.
_MSS_LIT = re.compile(r'"((?:[^"]*/)?)([A-Za-z0-9_]+\.mss(?:\.lua)?)"')


def stack_rewrite(script: str, prefix: str) -> str:
    """Prefix the basename of every .mss/.mss.lua literal in `script`.

    Both directions must move together: prefixing only loadState references
    would boot gen_rapids from t2_scenario_hub and then let it OVERWRITE the
    honest rapids_start/rapids_done with states minted from a contaminated
    boot -- the exact silent-wrong-artifact class the resolver selftest
    exists for.  Screenshot tags carry no .mss suffix and are untouched;
    comments mentioning state names get rewritten too, which is harmless.
    """
    if not prefix:
        return script
    if not re.fullmatch(r"[A-Za-z0-9_]+", prefix):
        raise ValueError(f"OT6_STACK={prefix!r}: prefix must be [A-Za-z0-9_]+")
    return _MSS_LIT.sub(lambda m: f'"{m.group(1)}{prefix}{m.group(2)}"', script)


def resolve_sidecar(ref, root):
    """Pick the sidecar file a "<path>.mss.lua" reference should embed.

    Scripts hardcode the MAIN tree's absolute path (Mesen's sandbox has no
    cwd, so the reference must be a fixed string).  THIS TREE'S OWN
    build/states therefore wins outright over the literal path -- the
    literal is a naming convention, not a claim about which tree's bytes the
    caller wants.  Composition is already tree-local everywhere else: LIB
    ignores the script's literal dofile path in exactly the same way.

    Precedence, per reference:
      1. <root>/build/states/<basename>       -- always wins if present
      2. the literal path, if it lies inside <root>
      3. literal exists but points OUT of <root> -> raise CrossTree
      4. nowhere -> None; embed nothing, the lib raises "sidecar not
         embedded" at loadState, which is already a clear failure

    Rule 1 is the fix.  An earlier pass consulted this tree only when the
    literal MISSED -- but the literal (a main-tree path) essentially always
    exists, so the fallback never fired, and a worktree that had legitimately
    re-minted a state for its own modified ROM still composed the MAIN
    tree's stale copy.

    Rule 3 refuses rather than silently borrowing.  A foreign tree's state
    was minted from a DIFFERENT ROM, so a run against it is a green that
    proves nothing; and reading it while that tree re-mints is a cross-tree
    race besides.  run.sh already takes this line for the settings pin
    ("Refusing the run beats reporting a green that never had the pins") --
    a fixture is no weaker a guarantee than a settings file.

    The MAIN tree cannot reach rule 3: there the literal IS the rule-1 path,
    so main-tree behavior is unchanged.
    """
    local, literal = root / "build" / "states" / Path(ref).name, Path(ref)
    if local.exists():
        return local
    if literal.exists():
        if not literal.resolve().is_relative_to(root):
            raise CrossTree(ref)
        return literal
    return None


def selftest() -> int:
    """Positive control for resolve_sidecar's precedence: `compose.py --selftest`.

    The bug this guards is a SILENT wrong answer -- composition that quietly
    embeds another tree's savestate -- so asserting "it composed fine" would
    itself pass for the wrong reason.  Each case below therefore pins WHICH
    file was chosen, and case 1 (the regression) is built so that the old
    literal-first code would have picked the other one.
    """
    import tempfile

    ok = True

    def check(label, got, want):
        nonlocal ok
        if got != want:
            ok = False
            print(f"  FAIL {label}\n       got  {got}\n       want {want}")
        else:
            print(f"  pass {label}")

    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp).resolve()
        main_tree, work = tmp / "ot6", tmp / "ot6" / ".claude" / "wt" / "a"
        for t in (main_tree, work):
            (t / "build" / "states").mkdir(parents=True)
        # A worktree nests INSIDE the main tree on disk, as real ones do --
        # so "outside this tree" cannot be a naive prefix test in reverse.
        m_state = main_tree / "build" / "states" / "s.mss.lua"
        w_state = work / "build" / "states" / "s.mss.lua"
        m_state.write_text('return "TUFJTg=="\n')
        w_state.write_text('return "V09SSw=="\n')
        ref = str(m_state)   # scripts hardcode the MAIN tree's path

        # 1. THE REGRESSION: both trees have it; the composing tree wins.
        check("worktree copy beats the hardcoded main-tree path",
              resolve_sidecar(ref, work), w_state)
        # 2. Main tree composing its own reference is untouched.
        check("main tree resolves its own literal",
              resolve_sidecar(ref, main_tree), m_state)
        # 3. Local copy missing + literal outside the tree -> refuse.
        w_state.unlink()
        try:
            resolve_sidecar(ref, work)
            check("cross-tree reference refused", "returned a path", "CrossTree")
        except CrossTree:
            check("cross-tree reference refused", "CrossTree", "CrossTree")
        # 4. Missing everywhere -> None (the lib raises at loadState).
        check("absent everywhere yields None",
              resolve_sidecar(str(main_tree / "build" / "states" / "nope.mss.lua"),
                              work), None)
        # 5. In-tree literal outside build/states still resolves (rule 2).
        odd = work / "fixtures"
        odd.mkdir()
        (odd / "x.mss.lua").write_text('return "WA=="\n')
        check("in-tree literal outside build/states still resolves",
              resolve_sidecar(str(odd / "x.mss.lua"), work), odd / "x.mss.lua")

    # -- stack_rewrite: both directions of a route must move together --
    src = ('local HUB = "/Users/x/ot6/build/states/scenario_hub.mss.lua"\n'
           'H.saveState("rapids_done.mss")\n'
           'H.screenshot("rapids_battle1")\n')
    got = stack_rewrite(src, "t2_")
    check("stack prefixes the boot sidecar reference",
          '"/Users/x/ot6/build/states/t2_scenario_hub.mss.lua"' in got, True)
    check("stack prefixes the emitted state name",
          'H.saveState("t2_rapids_done.mss")' in got, True)
    check("stack leaves screenshot tags alone",
          'H.screenshot("rapids_battle1")' in got, True)
    check("empty prefix is the identity", stack_rewrite(src, ""), src)
    try:
        stack_rewrite(src, "bad/../prefix")
        check("stack refuses a non-word prefix", "no raise", "ValueError")
    except ValueError:
        check("stack refuses a non-word prefix", "ValueError", "ValueError")

    print("selftest: " + ("ok" if ok else "FAILED"))
    return 0 if ok else 1


def main() -> int:
    if len(sys.argv) == 2 and sys.argv[1] == "--selftest":
        return selftest()
    # --sha <sidecar>: the same fingerprint the provenance lines carry, so a
    # hash seen in a run log can be checked against a state on disk.
    if len(sys.argv) == 3 and sys.argv[1] == "--sha":
        print(digest(payload(Path(sys.argv[2]))))
        return 0
    script_path, out_path = Path(sys.argv[1]), Path(sys.argv[2])
    script = script_path.read_text()
    lib = LIB.read_text()

    # Composing is NOT idempotent (the usage-example dofile line in the
    # inlined lib header would re-trigger inlining), so refuse re-composition.
    # run.sh runs already-composed files (first line = MARKER) directly.
    if script.startswith(MARKER):
        print(f"error: {script_path} is already composed; refusing to re-compose")
        return 1

    # Scenario stacking: rewrite state basenames BEFORE sidecar collection,
    # so the resolver sees (and embeds) the prefixed names.  Script only --
    # the lib's own .mss mentions are documentation, and rewriting the lib
    # would make the composed lib differ per prefix for no behavioral reason.
    stack = os.environ.get("OT6_STACK", "")
    if stack:
        script = stack_rewrite(script, stack)
        print(f"stack prefix {stack!r} applied to {script_path}")

    # Collect referenced savestate sidecars: any "<path>.mss.lua" string
    # literal in the script (scripts typically bind them to a STATE local).
    # resolve_sidecar() owns the precedence; see its docstring.
    states, sources = {}, {}
    for ref in dict.fromkeys(re.findall(r'"([^"]+\.mss\.lua)"', script)):
        try:
            p = resolve_sidecar(ref, ROOT)
        except CrossTree:
            print(f"error: {script_path} references {ref}, which exists only "
                  f"OUTSIDE this tree ({ROOT}).  Refusing to compose another "
                  f"tree's savestate: it was minted from a different ROM, so "
                  f"a run against it proves nothing.  Mint it here (make, or "
                  f"the generator that emits it), or seed this tree with "
                  f"tools/worktree-setup.sh.")
            return 1
        if p is None:
            continue
        b64 = payload(p)
        if b64:
            states[Path(ref).name], sources[Path(ref).name] = b64, p

    # Say WHICH sidecar got embedded, in the composed file itself.  A state
    # mismatch otherwise looks like a ROM bug: the run loads a fixture that
    # is subtly wrong and fails somewhere unrelated, with nothing anywhere
    # naming the file it actually came from.  The print() lands in the run
    # log (run.sh greps '^[ot6]', so it reaches the terminal too) and the
    # comment survives in the composed artifact for later inspection.
    preamble = [MARKER + "\n"]
    if states:
        for name, b64 in states.items():
            preamble.append(f"-- state {name} sha={digest(b64)} "
                            f"({len(b64)} b64 chars) <- {sources[name]}\n")
        preamble.append("OT6_STATES = {\n")
        for name, b64 in states.items():
            preamble.append(f'  ["{name}"] = "{b64}",\n')
        preamble.append("}\n")
        for name, b64 in states.items():
            preamble.append(f'print("[ot6] state {name} sha={digest(b64)} '
                            f'<- {sources[name]}")\n')

    out, replaced = list(preamble), False
    for line in script.splitlines(keepends=True):
        if not replaced and "dofile(" in line and "lib/ot6.lua" in line:
            out.append("local H = (function()\n")
            out.append(lib)
            out.append("\nend)()\n")
            replaced = True
        else:
            out.append(line)
    if not replaced:
        # script doesn't use the lib (e.g. smoke.lua); pass it through, marked
        out_path.write_text(MARKER + "\n" + script)
        print(f"composed {out_path} (no lib reference; copied as-is)")
        return 0

    out_path.write_text("".join(out))
    print(f"composed {out_path} ({len(states)} embedded savestate(s))")
    for name, b64 in states.items():
        print(f"  {name} sha={digest(b64)} <- {sources[name]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
