#!/bin/sh
# frontier_deps.sh <Makefile> -- emit the make prerequisites that make a
# frontier state's minted sidecar depend on its generator .lua and on both
# halves of the test library (lib/ot6.lua + lib/ot6_field.lua -- compose.py
# inlines the pair into every composed generator), so `make frontier`
# actually RUNS that state's recipe when any of them changes (the recipe's
# frontier_stamp.sh gate then decides mint-or-skip by content).  Without a
# declared prerequisite make never reconsiders the target, so the content
# gate would never get a chance to fire -- issue #2.
#
# The state->generator map is not maintained here; it is read straight out of
# the `$(call mint,...)` lines (plain and stacked) that already carry it, so
# a frontier link added to the Makefile is covered the moment it lands, with no
# second list to keep in sync (the Zozo route is adding links as we speak).
#
#   $(call mint,<state>,<generator>)           -> state, generator = fields 1,2
#   $(call mint,<state>,<generator>,<prefix>)  -> stacked; same fields 1,2
#
# Each emitted line ADDS prerequisites to a target the Makefile already gives a
# recipe; make merges the two prerequisite sets (only the Makefile side carries
# the recipe, so there is no "commands commented out" conflict).  The stack
# SEED rules (t2_/s2_/t3_scenario_hub) have no generator -- they cp a finished
# state -- and correctly match nothing here; their own gate tracks their source.
set -eu

mk="${1:?usage: frontier_deps.sh <Makefile>}"

echo "# AUTOGENERATED by tools/tests/lib/frontier_deps.sh -- do not edit."
echo "# Ties each frontier state to its generator + both lib halves (issue #2)."

LIBS='tools/tests/lib/ot6.lua tools/tests/lib/ot6_field.lua'

grep -oE '\$\(call mint,[A-Za-z0-9_]+,[A-Za-z0-9_]+\)' "$mk" \
  | sed -E "s#.*mint,([A-Za-z0-9_]+),([A-Za-z0-9_]+)\).*#build/states/\1.mss.lua: tools/tests/\2.lua $LIBS#"

grep -oE '\$\(call mint,[A-Za-z0-9_]+,[A-Za-z0-9_]+,[A-Za-z0-9_]*\)' "$mk" \
  | sed -E "s#.*mint,([A-Za-z0-9_]+),([A-Za-z0-9_]+),[A-Za-z0-9_]*\).*#build/states/\1.mss.lua: tools/tests/\2.lua $LIBS#"
