#!/bin/sh
# savestate_stamp.sh: the one definition of a generated fixture's provenance
# signature.
#
# Usage:
#   savestate_stamp.sh write <state> <generator> <ancestor|-> [extra ...]
#   savestate_stamp.sh sig   <generator> [extra ...]
#
# The signature hashes GATE_CONTRACT, the generator, and the three lib
# halves compose.py inlines into every composed script (ot6.lua,
# ot6_field.lua, ot6_contract.lua, in that order), plus any declared extra
# inputs (SRAM checkpoints hash manifest then payloads).  Content-keyed
# throughout: an mtime bump changes no signature.
#
# A stamp file holds three things, one per line:
#
#     <sha256(GATE_CONTRACT ++ gen ++ ot6.lua ++ ot6_field.lua ++
#             ot6_contract.lua ++ extras...)> <gen> [extras...]
#     artifact <sha256(build/states/<state>.mss)>
#     ancestor <path> <sha256(<path> file bytes)>        (non-root states only)
#
# The artifact line binds stamp -> generated bytes, so replacing the .mss
# without regenerating is detected.  The ancestor line binds stamp -> the
# predecessor's stamp file (prev= edges) or the checkpoint's manifest.json
# (checkpoint= edges), so the whole chain is verifiable transitively on disk
# down to a power-on root.  compose.py's stamp_check verifies every line;
# `compose.py --check-states` asks it of the whole tree.
set -u

# The GATE_CONTRACT version, a fixed input to every signature.  Bumping it
# stales every stamp in existence and forces a full regeneration.  Both
# sides of the comparison (the `generate` edge and compose.py) shell into
# this file, so there is exactly one definition to bump.
GATE_CONTRACT='ot6-provenance/v1'

# OT6_ROOT lets selftests and compose.py point the sig at another tree; the
# default is the real tree this script lives in (lib/ -> tests/ -> tools/ ->
# root).
ROOT="${OT6_ROOT:-$(cd "$(dirname "$0")/../../.." && pwd)}"
STATES="$ROOT/build/states"

# sha256(<generator source> ++ <battle core> ++ <nav half> ++ <contract
# half>) plus the generator's name and the extras' paths.  Order is fixed,
# the same order compose.py inlines them, so the digest is reproducible
# from either side.
sig() {
  gen="$1"
  shift
  files="$ROOT/tools/tests/$gen.lua
$ROOT/tools/tests/lib/ot6.lua
$ROOT/tools/tests/lib/ot6_field.lua
$ROOT/tools/tests/lib/ot6_contract.lua"
  # Every fixed input must exist before hashing: the digest pipeline's `cat`
  # cannot fail it (a pipeline swallows the status), so a typo'd generator
  # would otherwise hash the remaining files and return that as a signature.
  printf '%s\n' "$files" | while IFS= read -r f; do
    [ -f "$f" ] ||
      { echo "savestate_stamp: missing input '$f'" >&2; exit 2; }
  done || exit 2
  extras=""
  for extra in "$@"; do
    case "$extra" in /*|*..*) echo "savestate_stamp: unsafe extra '$extra'" >&2; exit 2 ;; esac
    [ -f "$ROOT/$extra" ] ||
      { echo "savestate_stamp: missing extra '$ROOT/$extra'" >&2; exit 2; }
    files="$files
$ROOT/$extra"
    extras="$extras $extra"
  done
  # The GATE_CONTRACT version leads the byte stream, so bumping the constant
  # above moves every signature at once (see its comment).
  digest=$(
    { printf '%s\n' "$GATE_CONTRACT"
      printf '%s\n' "$files" | while IFS= read -r file; do cat "$file"; done
    } | shasum -a 256 | cut -c1-64
  )
  printf '%s %s%s' "$digest" "$gen" "$extras"
}

# sha256 of one file, bare.  Used for the artifact and ancestor bindings.
filehash() {
  shasum -a 256 "$1" | cut -c1-64
}

cmd="${1:?usage: savestate_stamp.sh write|sig ...}"
case "$cmd" in
  sig)
    gen="${2:?sig needs a generator}"; shift 2
    sig "$gen" "$@"
    ;;
  write)
    state="${2:?write needs a state}"; gen="${3:?write needs a generator}"
    ancestor="${4:?write needs an ancestor (a .stamp/manifest.json path relative to the tree root, or - for a power-on root)}"
    shift 4
    # Bind the artifact first: a stamp that cannot name the bytes it
    # vouches for must not exist.  The .mss was published by the
    # same generating command a moment ago, so a miss here is a wiring bug.
    mss="$STATES/$state.mss"
    [ -f "$mss" ] ||
      { echo "savestate_stamp: no generated artifact '$mss' to bind" >&2; exit 2; }
    artifact=$(filehash "$mss")
    anc_hash=""
    if [ "$ancestor" != "-" ]; then
      case "$ancestor" in /*|*..*)
        echo "savestate_stamp: unsafe ancestor '$ancestor'" >&2; exit 2 ;;
      esac
      [ -f "$ROOT/$ancestor" ] ||
        { echo "savestate_stamp: missing ancestor '$ROOT/$ancestor'" >&2; exit 2; }
      anc_hash=$(filehash "$ROOT/$ancestor")
    fi
    # Everything is computed; only now may the old stamp be replaced.
    sigline=$(sig "$gen" "$@") || exit 2
    {
      printf '%s\n' "$sigline"
      printf 'artifact %s\n' "$artifact"
      [ "$ancestor" = "-" ] ||
        printf 'ancestor %s %s\n' "$ancestor" "$anc_hash"
    } > "$STATES/$state.stamp"
    ;;
  *)
    echo "savestate_stamp.sh: unknown command '$cmd'" >&2
    exit 2
    ;;
esac
