#!/bin/sh
# savestate_stamp.sh: the one definition of a generated fixture's provenance
# signature and compatibility bindings.
#
# Usage:
#   savestate_stamp.sh write  <state> <generator> <ancestor|-> [extra ...]
#   savestate_stamp.sh sig    <generator> [extra ...]
#   savestate_stamp.sh gensig <generator> [extra ...]
#   savestate_stamp.sh romsig
#
# The signature (`sig`) hashes GATE_CONTRACT, the generator, and the three
# lib halves compose.py inlines into every composed script (ot6.lua,
# ot6_field.lua, ot6_contract.lua, in that order), plus any declared extra
# inputs (SRAM checkpoints hash manifest then payloads).  Content-keyed
# throughout: an mtime bump changes no signature.
#
# A stamp file holds, one per line:
#
#     <sha256(GATE_CONTRACT ++ gen ++ ot6.lua ++ ot6_field.lua ++
#             ot6_contract.lua ++ extras...)> <gen> [extras...]
#     rom <sha256(the ROM the run booted)>
#     generator <sha256(GATE_CONTRACT ++ gen ++ extras...)>
#     lib <path> <sha256(<path>)>                      (one per lib half)
#     artifact <sha256(build/states/<state>.mss)>
#     ancestor <path> <sha256(<path> file bytes)>        (non-root states only)
#
# Provenance versus compatibility (docs/TESTING.md): the sig and lib lines
# record exactly which harness sources produced the fixture.  They are kept
# as provenance and are NOT what decides freshness.  The rom and generator
# lines are the compatibility bindings: a fixture is stale when the ROM it
# runs on differs from the ROM it was captured on, or when its own
# generator (its play, not the shared lib halves) changed.  The artifact
# line binds stamp -> generated bytes, so replacing the .mss without
# regenerating is detected.  The ancestor line binds stamp -> the
# predecessor's stamp file (prev= edges) or the checkpoint's manifest.json
# (checkpoint= edges), so the whole chain is verifiable transitively on disk
# down to a power-on root.  compose.py's stamp_check verifies every line;
# `compose.py --check-states` asks it of the whole tree.
#
# A stamp written before the rom/generator lines existed carries neither.
# compose.py keeps such a stamp on the older, conservative whole-sig rule
# until the fixture is regenerated; nothing here ever invents a ROM
# identity for it.  `compose.py --adopt-stamps` appends the missing lines
# to such a stamp only when the tree's own records prove them: the sig
# still matches the current sources, the artifact verifies, and ninja's
# build log shows the ROM content latch last ran before the generate edge
# and its copy is the current ROM (see adopt_stamps in compose.py).
set -u

# The GATE_CONTRACT version, a fixed input to every signature (sig and
# gensig both).  Bumping it stales every stamp in existence and forces a
# full regeneration.  Both sides of the comparison (the `generate` edge and
# compose.py) shell into this file, so there is exactly one definition to
# bump.
GATE_CONTRACT='ot6-provenance/v1'

# OT6_ROOT lets selftests and compose.py point the sig at another tree; the
# default is the real tree this script lives in (lib/ -> tests/ -> tools/ ->
# root).
ROOT="${OT6_ROOT:-$(cd "$(dirname "$0")/../../.." && pwd)}"
STATES="$ROOT/build/states"
# The ROM a generation run boots: run.sh's own default, overridable the same
# way (OT6_ROM), so the stamp records the ROM that actually ran.  compose.py
# compares the recorded identity against the tree's build/ot6.sfc.
ROM="${OT6_ROM:-$ROOT/build/ot6.sfc}"
LIB_HALVES="tools/tests/lib/ot6.lua
tools/tests/lib/ot6_field.lua
tools/tests/lib/ot6_contract.lua"

# check_inputs <newline-separated files>: every fixed input must exist
# before hashing: the digest pipeline's `cat` cannot fail it (a pipeline
# swallows the status), so a typo'd generator would otherwise hash the
# remaining files and return that as a signature.
check_inputs() {
  printf '%s\n' "$1" | while IFS= read -r f; do
    [ -f "$f" ] ||
      { echo "savestate_stamp: missing input '$f'" >&2; exit 2; }
  done || exit 2
}

# extra_files <extra>...: refuse unsafe or missing extras; print the
# absolute paths, one per line.
extra_files() {
  for extra in "$@"; do
    case "$extra" in /*|*..*) echo "savestate_stamp: unsafe extra '$extra'" >&2; exit 2 ;; esac
    [ -f "$ROOT/$extra" ] ||
      { echo "savestate_stamp: missing extra '$ROOT/$extra'" >&2; exit 2; }
    printf '%s\n' "$ROOT/$extra"
  done
}

# digest_of <newline-separated files>: sha256(GATE_CONTRACT ++ files...).
# The GATE_CONTRACT version leads the byte stream, so bumping the constant
# above moves every signature at once (see its comment).
digest_of() {
  { printf '%s\n' "$GATE_CONTRACT"
    printf '%s\n' "$1" | while IFS= read -r file; do cat "$file"; done
  } | shasum -a 256 | cut -c1-64
}

# sha256(<generator source> ++ <battle core> ++ <nav half> ++ <contract
# half> ++ extras) plus the generator's name and the extras' paths.  Order
# is fixed, the same order compose.py inlines them, so the digest is
# reproducible from either side.  This is the provenance signature: it
# names the sources exactly and is kept for that; freshness is decided by
# gensig and romsig below.
sig() {
  gen="$1"
  shift
  files="$ROOT/tools/tests/$gen.lua"
  for h in $LIB_HALVES; do files="$files
$ROOT/$h"; done
  check_inputs "$files" || exit 2
  ex=$(extra_files "$@") || exit 2
  [ -z "$ex" ] || files="$files
$ex"
  extras=""
  for extra in "$@"; do extras="$extras $extra"; done
  printf '%s %s%s' "$(digest_of "$files")" "$gen" "$extras"
}

# sha256(GATE_CONTRACT ++ <generator source> ++ extras): the generator's own
# signature, the lib halves left out.  This is the compatibility binding
# for "did this fixture's play change?"  Per docs/TESTING.md a logging,
# assertion, or controller-policy edit in the shared lib halves does not by
# itself make a legitimately reached snapshot illegitimate, so those are
# not inputs here.
gensig() {
  gen="$1"
  shift
  files="$ROOT/tools/tests/$gen.lua"
  check_inputs "$files" || exit 2
  ex=$(extra_files "$@") || exit 2
  [ -z "$ex" ] || files="$files
$ex"
  digest_of "$files"
}

# sha256 of the ROM the run boots: the compatibility binding for "is this
# fixture a snapshot of the machine this tree builds?"  Changed ROM
# code/layout can invalidate a machine snapshot.  A missing ROM is a hard
# error; a stamp must never guess its ROM.
romsig() {
  [ -f "$ROM" ] ||
    { echo "savestate_stamp: no ROM at '$ROM' to identify" >&2; exit 2; }
  shasum -a 256 "$ROM" | cut -c1-64
}

# sha256 of one file, bare.  Used for the artifact, ancestor and lib
# bindings.
filehash() {
  shasum -a 256 "$1" | cut -c1-64
}

cmd="${1:?usage: savestate_stamp.sh write|sig|gensig|romsig ...}"
case "$cmd" in
  sig)
    gen="${2:?sig needs a generator}"; shift 2
    sig "$gen" "$@"
    ;;
  gensig)
    gen="${2:?gensig needs a generator}"; shift 2
    gensig "$gen" "$@"
    ;;
  romsig)
    romsig
    ;;
  write)
    state="${2:?write needs a state}"; gen="${3:?write needs a generator}"
    ancestor="${4:?write needs an ancestor (a .stamp/manifest.json path relative to the tree root, or - for a power-on root)}"
    shift 4
    # Bind the artifact first: a stamp that cannot name the bytes it
    # records must not exist.  The .mss was published by the
    # same generating command a moment ago, so a miss here is a wiring bug.
    mss="$STATES/$state.mss"
    [ -f "$mss" ] ||
      { echo "savestate_stamp: no generated artifact '$mss' to bind" >&2; exit 2; }
    artifact=$(filehash "$mss")
    anc_hash=""
    if [ "$ancestor" != "-" ]; then
      case "$ancestor" in /*|*..*)
        echo "savestate_stamp: unsafe ancestor '$ancestor'" >&2; exit 2 ;;
      esac
      [ -f "$ROOT/$ancestor" ] ||
        { echo "savestate_stamp: missing ancestor '$ROOT/$ancestor'" >&2; exit 2; }
      anc_hash=$(filehash "$ROOT/$ancestor")
    fi
    # The compatibility bindings: the ROM this run booted and the
    # generator's own signature.  Each is a hard error when it cannot be
    # computed; a stamp never records a guessed ROM.
    rom_hash=$(romsig) || exit 2
    gen_hash=$(gensig "$gen" "$@") || exit 2
    # Everything is computed; only now may the old stamp be replaced.
    sigline=$(sig "$gen" "$@") || exit 2
    {
      printf '%s\n' "$sigline"
      printf 'rom %s\n' "$rom_hash"
      printf 'generator %s\n' "$gen_hash"
      for h in $LIB_HALVES; do
        printf 'lib %s %s\n' "$h" "$(filehash "$ROOT/$h")"
      done
      printf 'artifact %s\n' "$artifact"
      [ "$ancestor" = "-" ] ||
        printf 'ancestor %s %s\n' "$ancestor" "$anc_hash"
    } > "$STATES/$state.stamp"
    ;;
  *)
    echo "savestate_stamp.sh: unknown command '$cmd'" >&2
    exit 2
    ;;
esac
