#!/bin/sh
# Drives waves of run.sh workers through the shared-emulator gate against a
# scratch cache (OT6_MESEN_CACHE) and stops each one at the gate
# (OT6_PROVISION_PROBE_OUT), so nothing launches and no Gatekeeper scan is
# paid.  Checks the handoff #242 broke: a cold cache reached by many workers
# at once is built exactly once and every worker is handed the finished
# bundle; a warm cache is built zero times; a stale stamp (a Mesen upgrade)
# is rebuilt exactly once, again with every worker served.
#
# The cold waves stagger their launches by a few milliseconds, the spread
# compose.py's run time gave the release qualification's first wave, which
# is what put a worker's readiness look before the builder's last step and
# its lock grab after it.  That interleaving is a matter of milliseconds,
# so the cold waves are repeated; build/lab/run-sh-race/ holds the
# before/after counts this was tuned on.
set -u
ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
TMP=$(mktemp -d "${TMPDIR:-/tmp}/ot6-shared-emulator-selftest.XXXXXXXX") || exit 1
trap 'rm -rf "$TMP"' EXIT INT TERM
CACHE="$TMP/cache"
APP="$CACHE/Mesen-test.app"
N=16
fails=0
fail() { echo "  FAIL  $*"; fails=$((fails + 1)); }

# Already composed (carries compose.py's marker), so run.sh skips compose.py
# and every worker reaches the gate within milliseconds of the others.
printf -- '-- AUTOGENERATED by lib/compose.py\nprint("never runs")\n' > "$TMP/probe.lua"

wave() {  # <label> <stagger seconds> <builds wanted>
  i=1
  while [ "$i" -le "$N" ]; do
    ( OT6_MESEN_CACHE="$CACHE" OT6_PROVISION_PROBE_OUT="$TMP/$1.$i.app" OT6_WORKER="$1$i" \
        "$ROOT/tools/tests/run.sh" "$TMP/probe.lua" "$TMP/$1.$i.log" > "$TMP/$1.$i.out" 2>&1
      echo $? > "$TMP/$1.$i.code" ) &
    [ "$2" = 0 ] || sleep "$2"
    i=$((i + 1))
  done
  wait
  i=1
  while [ "$i" -le "$N" ]; do
    code=$(cat "$TMP/$1.$i.code")
    [ "$code" = 0 ] || fail "$1: worker $i exit $code: $(tail -n 1 "$TMP/$1.$i.out")"
    [ "$(cat "$TMP/$1.$i.app" 2>/dev/null)" = "$APP" ] || fail "$1: worker $i was not handed $APP"
    i=$((i + 1))
  done
  builds=$(cat "$TMP/$1".*.out | grep -c 'creating shared test emulator')
  if [ "$builds" = "$3" ]; then printf '  pass  %s: %s build(s), all %s workers served\n' "$1" "$builds" "$N"
  else fail "$1: $builds build(s), want $3"; fi
}

bundle_ok() {  # the shape the gate promises, and nothing the build leaves behind
  [ -x "$APP/Contents/MacOS/Mesen" ] || fail "$1: no executable at $APP/Contents/MacOS/Mesen"
  [ ! -e "$APP/Contents/MacOS/settings.json" ] || fail "$1: settings.json survived into the shared copy"
  [ "$(ls "$APP")" = Contents ] || fail "$1: the bundle holds more than Contents: $(ls "$APP" | tr '\n' ' ')"
  [ "$(cat "$APP.stamp")" = "$(stat -Lf '%z %m' "$ROOT/tools/Mesen.app/Contents/MacOS/Mesen")" ] || fail "$1: stamp does not name the source binary"
  [ ! -e "$CACHE/.build.lock" ] || fail "$1: the lock was left held"
  [ -z "$(ls -d "$CACHE"/.build.* 2>/dev/null)" ] || fail "$1: build leftovers: $(ls -d "$CACHE"/.build.* | tr '\n' ' ')"
}

# The override's default is the machine-wide path: a worker given no
# OT6_MESEN_CACHE provisions under HOME, here a scratch one.
( HOME="$TMP/home" OT6_PROVISION_PROBE_OUT="$TMP/default.app" \
    "$ROOT/tools/tests/run.sh" "$TMP/probe.lua" "$TMP/default.log" > "$TMP/default.out" 2>&1 ) || fail "default cache: $(tail -n 1 "$TMP/default.out")"
if [ "$(cat "$TMP/default.app" 2>/dev/null)" = "$TMP/home/Library/Caches/ot6/Mesen-test.app" ]; then
  echo "  pass  OT6_MESEN_CACHE unset provisions under \$HOME/Library/Caches/ot6"
else fail "OT6_MESEN_CACHE unset provisioned at '$(cat "$TMP/default.app" 2>/dev/null)'"; fi
rm -rf "$TMP/home"

k=1
while [ "$k" -le 6 ]; do
  rm -rf "$CACHE"
  wave "cold$k" 0.002 1
  bundle_ok "cold$k"
  k=$((k + 1))
done
wave warm 0 0
bundle_ok warm
printf 'stale' > "$APP.stamp"
wave stale 0.002 1
bundle_ok stale

if [ "$fails" -ne 0 ]; then echo "shared emulator selftest: $fails FAILURE(S)"; exit 1; fi
echo "shared emulator selftest: ok"
