#!/bin/sh
# Drives waves of run.sh workers through the shared-emulator gate against a
# scratch cache (OT6_MESEN_CACHE) and stops each one at the gate
# (OT6_PROVISION_PROBE_OUT), so nothing launches and no Gatekeeper scan is
# paid.  Checks the handoff #242 broke: a cold cache reached by many workers
# at once is built exactly once and every worker is handed the finished
# bundle; a warm cache is built zero times; a stale stamp (a Mesen upgrade)
# is rebuilt exactly once, again with every worker served.
#
# What makes "exactly once" hold is the build lock's mutual exclusion, so
# that is measured first, directly: rounds of concurrent takers of one lock
# (run.sh --take-lock, the primitive the gate uses), each round exactly one
# winner.  #371 was that primitive failing: px13's mkdir(1) (uutils
# coreutils 0.10.0) let several concurrent takers win, two workers built at
# once, and the second build's mv nested it inside the first's bundle.  The
# waves catch that only when two workers' looks happen to coincide; the
# rounds catch it every run.  bundle_ok also lists the bundle's hidden
# entries, where that nested build hid.
#
# The cold waves stagger their launches by a few milliseconds, the spread
# compose.py's run time gave the release qualification's first wave, which
# is what put a worker's readiness look before the builder's last step and
# its lock grab after it.  That interleaving is a matter of milliseconds,
# so the cold waves are repeated; build/lab/run-sh-race/ holds the
# before/after counts this was tuned on.
set -u
ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
TMP=$(mktemp -d "${TMPDIR:-/tmp}/ot6-shared-emulator-selftest.XXXXXXXX") || exit 1
trap 'rm -rf "$TMP"' EXIT INT TERM
CACHE="$TMP/cache"
# The shapes run.sh provisions: a bundle on macOS, a directory holding the
# single-file binary on Linux (docs/TOOLING.md "Linux worker").
if [ "$(uname -s)" = Darwin ]; then
  APP="$CACHE/Mesen-test.app"; BIN_SUB=/Contents/MacOS; TOP=Contents
  SRC_BIN="$ROOT/tools/Mesen.app/Contents/MacOS/Mesen"
  DEFAULT_CACHE=Library/Caches/ot6; DEFAULT_APP=Mesen-test.app
  file_stamp() { stat -Lf '%z %m' "$1"; }
else
  APP="$CACHE/Mesen-test"; BIN_SUB=; TOP=Mesen
  SRC_BIN="$ROOT/tools/Mesen-linux/Mesen"
  DEFAULT_CACHE=.cache/ot6; DEFAULT_APP=Mesen-test
  file_stamp() { stat -Lc '%s %Y' "$1"; }
fi
# A machine with the pin deployed (run.sh: ~/mesen-pins/<commit>/) provisions
# that build, into a shared copy named after the pin
PIN_COMMIT=$(cut -d' ' -f3 "$ROOT/tools/mesen/EMULATOR" 2>/dev/null)
PIN_DIR="$HOME/mesen-pins/$PIN_COMMIT"
PIN12=$(echo "$PIN_COMMIT" | cut -c1-12)
# (the directory as deployed: on Linux the binary with its Mesen.buildinfo
# beside it, so the shared copy holds both; tools/mesen/README.md
# "Deploying").  A fresh clone has no tools/Mesen-linux at all: the pin is
# the only build there.
PINNED=""
if [ -n "$PIN_COMMIT" ] && [ "$(uname -s)" = Darwin ] && [ -x "$PIN_DIR/Mesen.app/Contents/MacOS/Mesen" ]; then
  APP="$CACHE/Mesen-test-$PIN12.app"; SRC_BIN="$PIN_DIR/Mesen.app/Contents/MacOS/Mesen"
  DEFAULT_APP="Mesen-test-$PIN12.app"; PINNED=1
elif [ -n "$PIN_COMMIT" ] && [ "$(uname -s)" != Darwin ] && [ -x "$PIN_DIR/Mesen" ]; then
  APP="$CACHE/Mesen-test-$PIN12"; SRC_BIN="$PIN_DIR/Mesen"
  DEFAULT_APP="Mesen-test-$PIN12"; PINNED=1
  TOP=$(ls -A "$PIN_DIR" | grep -v '^settings' | tr '\n' ' ' | sed 's/ $//')
fi
N=16
fails=0
fail() { echo "  FAIL  $*"; fails=$((fails + 1)); }

# Already composed (carries compose.py's marker), so run.sh skips compose.py
# and every worker reaches the gate within milliseconds of the others.
printf -- '-- AUTOGENERATED by lib/compose.py\nprint("never runs")\n' > "$TMP/probe.lua"

wave() {  # <label> <stagger seconds> <builds wanted>
  i=1
  while [ "$i" -le "$N" ]; do
    ( OT6_MESEN_CACHE="$CACHE" OT6_PROVISION_PROBE_OUT="$TMP/$1.$i.app" OT6_WORKER="$1$i" \
        "$ROOT/tools/tests/run.sh" "$TMP/probe.lua" "$TMP/$1.$i.log" > "$TMP/$1.$i.out" 2>&1
      echo $? > "$TMP/$1.$i.code" ) &
    [ "$2" = 0 ] || sleep "$2"
    i=$((i + 1))
  done
  wait
  i=1
  while [ "$i" -le "$N" ]; do
    code=$(cat "$TMP/$1.$i.code")
    [ "$code" = 0 ] || fail "$1: worker $i exit $code: $(tail -n 1 "$TMP/$1.$i.out")"
    [ "$(cat "$TMP/$1.$i.app" 2>/dev/null)" = "$APP" ] || fail "$1: worker $i was not handed $APP"
    i=$((i + 1))
  done
  builds=$(cat "$TMP/$1".*.out | grep -c 'creating shared test emulator')
  if [ "$builds" = "$3" ]; then printf '  pass  %s: %s build(s), all %s workers served\n' "$1" "$builds" "$N"
  else
    fail "$1: $builds build(s), want $3"
    # #371: which workers built, and what each one's look under the lock saw
    grep -H 'creating shared test emulator' "$TMP/$1".*.out | sed "s|^$TMP/|        |"
  fi
}

bundle_ok() {  # the shape the gate promises, and nothing the build leaves behind
  [ -x "$APP$BIN_SUB/Mesen" ] || fail "$1: no executable at $APP$BIN_SUB/Mesen"
  [ ! -e "$APP$BIN_SUB/settings.json" ] || fail "$1: settings.json survived into the shared copy"
  [ "$(ls -A "$APP" | tr '\n' ' ' | sed 's/ $//')" = "$TOP" ] || fail "$1: the bundle holds more than $TOP: $(ls -A "$APP" | tr '\n' ' ')"
  [ "$(cat "$APP.stamp")" = "$(file_stamp "$SRC_BIN")" ] || fail "$1: stamp does not name the source binary"
  [ ! -e "$CACHE/.build.lock" ] || fail "$1: the lock was left held"
  [ -z "$(ls -d "$CACHE"/.build.* 2>/dev/null)" ] || fail "$1: build leftovers: $(ls -d "$CACHE"/.build.* | tr '\n' ' ')"
}

# The override's default is the machine-wide path: a worker given no
# OT6_MESEN_CACHE provisions under HOME, here a scratch one -- holding the
# machine's deployed pin (a link to it), as a fresh clone would find it.
mkdir -p "$TMP/home/mesen-pins"
[ -n "$PINNED" ] && ln -s "$PIN_DIR" "$TMP/home/mesen-pins/$PIN_COMMIT"
( HOME="$TMP/home" XDG_CACHE_HOME= OT6_PROVISION_PROBE_OUT="$TMP/default.app" \
    "$ROOT/tools/tests/run.sh" "$TMP/probe.lua" "$TMP/default.log" > "$TMP/default.out" 2>&1 ) || fail "default cache: $(tail -n 1 "$TMP/default.out")"
if [ "$(cat "$TMP/default.app" 2>/dev/null)" = "$TMP/home/$DEFAULT_CACHE/$DEFAULT_APP" ]; then
  echo "  pass  OT6_MESEN_CACHE unset provisions under \$HOME/$DEFAULT_CACHE"
else fail "OT6_MESEN_CACHE unset provisioned at '$(cat "$TMP/default.app" 2>/dev/null)'"; fi
rm -rf "$TMP/home"

# The lock: R rounds of N concurrent takers, exactly one winner each.
R=60
r=1; multi=0; none=0
while [ "$r" -le "$R" ]; do
  rm -rf "$TMP/lock" "$TMP/go" "$TMP"/won.*
  i=1
  while [ "$i" -le "$N" ]; do
    ( "$ROOT/tools/tests/run.sh" --take-lock "$TMP/lock" "$TMP/go" && : > "$TMP/won.$i" ) &
    i=$((i + 1))
  done
  sleep 0.2; : > "$TMP/go"   # every taker is spinning at the line by now
  wait
  won=$(ls "$TMP"/won.* 2>/dev/null | wc -l | tr -d ' ')
  [ "$won" -gt 1 ] && multi=$((multi + 1))
  [ "$won" -lt 1 ] && none=$((none + 1))
  r=$((r + 1))
done
rm -rf "$TMP/lock" "$TMP/go" "$TMP"/won.*
if [ "$multi" = 0 ] && [ "$none" = 0 ]; then
  printf '  pass  the build lock: %s rounds of %s concurrent takers, one winner each\n' "$R" "$N"
else
  fail "the build lock: of $R rounds of $N concurrent takers, $multi had more than one winner and $none had none"
fi

k=1
while [ "$k" -le 6 ]; do
  rm -rf "$CACHE"
  wave "cold$k" 0.002 1
  bundle_ok "cold$k"
  k=$((k + 1))
done
wave warm 0 0
bundle_ok warm
printf 'stale' > "$APP.stamp"
wave stale 0.002 1
bundle_ok stale

if [ "$fails" -ne 0 ]; then echo "shared emulator selftest: $fails FAILURE(S)"; exit 1; fi
echo "shared emulator selftest: ok"
