#!/usr/bin/env python3
# ------------------------------------------------------------------------------
# gen_shield_glyphs.py -- the HUD's shield-with-count tiles, one per count
#
# Writes ff6/src/battle/ot6_shield_glyphs.inc: Ot6ShieldGlyphs, 99 2bpp 8x8
# tiles, tile n-1 = a shield showing the number n (#292).  The HUD uploads
# the tile for a monster's live count into that monster slot's own font cell
# (ot6_hud.asm), so every count from 1 to 99 draws true.
#
# Counts 1-9: the shield the HUD has always drawn, one 3x5 numeral in white
# at columns 2-4.  Counts 1-6 come out byte-identical to the hand-drawn tiles
# they replace (asserted below).  Counts 10-99: a solid shield with two 3x5
# numerals at columns 0-2 and 5-7, which is the only way two digits fit
# eight pixels.
#
# Colors: 1 = outline, 2 = shield fill, 3 = numeral (plane 0 = bit 0,
# plane 1 = bit 1; each row is stored plane 0 then plane 1).
#
#   python3 ff6/tools/gen_shield_glyphs.py          # rewrite the .inc
#   python3 ff6/tools/gen_shield_glyphs.py --check  # exit 1 if it is stale
#
# stdlib only.
# ------------------------------------------------------------------------------

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "battle", "ot6_shield_glyphs.inc")

DIGITS = {
    0: [".X.", "X.X", "X.X", "X.X", ".X."],
    1: [".X.", "XX.", ".X.", ".X.", "XXX"],
    2: ["XX.", "..X", ".X.", "X..", "XXX"],
    3: ["XX.", "..X", ".X.", "..X", "XX."],
    4: ["X.X", "X.X", "XXX", "..X", "..X"],
    5: ["XXX", "X..", "XX.", "..X", "XXX"],
    6: [".XX", "X..", "XXX", "X.X", "XXX"],
    7: ["XXX", "..X", ".X.", ".X.", ".X."],
    8: ["XXX", "X.X", "XXX", "X.X", "XXX"],
    9: ["XXX", "X.X", "XXX", "..X", "XX."],
}

# the one-numeral shield (rows 0-7)
SHIELD_1 = [
    ".111111.",
    "12222221",
    "12222221",
    "12222221",
    ".122221.",
    "..1221..",
    "...11...",
    "........",
]

# the two-numeral shield: the numerals fill all eight columns, so there is
# no room for the side outline; a dark body behind them keeps them as sharp
# as the '?' cells beside them (white on a dark edge), and the grey rim at
# the top and the grey point below keep the shield's shape.  (The one-numeral
# shield's grey body behind white numerals edge to edge read washed out in
# game: build/attempts/wt/tiers-hud-school/, the #292 mock-ups.)
SHIELD_2 = [
    ".222222.",
    "11111111",
    "11111111",
    "11111111",
    "11111111",
    "11111111",
    ".211112.",
    "..2222..",
]

# the six hand-drawn tiles this table replaces (ot6_hud.asm before #292)
OLD = {
    1: "7e 00 91 7e b1 7e 91 7e 52 3c 3c 38 18 00 00 00",
    2: "7e 00 b1 7e 89 7e 91 7e 62 3c 3c 38 18 00 00 00",
    3: "7e 00 b1 7e 89 7e 91 7e 4a 3c 34 38 18 00 00 00",
    4: "7e 00 a9 7e a9 7e b9 7e 4a 3c 2c 18 18 00 00 00",
    5: "7e 00 b9 7e a1 7e b1 7e 4a 3c 3c 38 18 00 00 00",
    6: "7e 00 99 7e a1 7e b9 7e 6a 3c 3c 38 18 00 00 00",
}


def stamp(rows, digit, col):
    rows = [list(r) for r in rows]
    for r, pat in enumerate(DIGITS[digit]):
        for c, ch in enumerate(pat):
            if ch == "X":
                rows[1 + r][col + c] = "3"
    return ["".join(r) for r in rows]


def encode(rows):
    out = []
    for row in rows:
        p0 = p1 = 0
        for c, ch in enumerate(row):
            v = 0 if ch == "." else int(ch)
            p0 |= (v & 1) << (7 - c)
            p1 |= ((v >> 1) & 1) << (7 - c)
        out += [p0, p1]
    return bytes(out)


def tile(n):
    if n < 10:
        return encode(stamp(SHIELD_1, n, 2))
    return encode(stamp(stamp(SHIELD_2, n // 10, 0), n % 10, 5))


def render():
    for n, hexs in OLD.items():
        assert tile(n) == bytes.fromhex(hexs), "count %d no longer matches the old art" % n
    lines = [
        "; generated by ff6/tools/gen_shield_glyphs.py; do not edit by hand.",
        "; Ot6ShieldGlyphs: tile n-1 is the HUD shield showing the count n,",
        "; for n = 1..99 (2bpp, 16 bytes a tile).",
        "",
        "Ot6ShieldGlyphs:",
    ]
    for n in range(1, 100):
        b = tile(n)
        lines.append("; %d" % n)
        for k in (0, 8):
            lines.append("        .byte   " + ",".join("$%02x" % x for x in b[k:k + 8]))
    return "\n".join(lines) + "\n"


def main():
    text = render()
    if "--check" in sys.argv[1:]:
        cur = open(OUT).read() if os.path.exists(OUT) else ""
        if cur != text:
            print("ot6_shield_glyphs.inc is stale: python3 ff6/tools/gen_shield_glyphs.py")
            return 1
        print("ot6_shield_glyphs.inc is current")
        return 0
    with open(OUT, "w") as f:
        f.write(text)
    print("wrote %s (99 tiles)" % os.path.relpath(OUT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
